
export interface Problem {
  id: string;
  list: "interview" | "neetcode150";
  category: string;    // e.g. "Arrays & Hashing"
  tag: string;         // difficulty / flavor
  title: string;
  prompt: string;      // short statement
  description?: string; // fuller explanation shown outside the editor
  solution: string[];  // commented JS solution, line by line
  starter?: string;    // starter code for the Code Lab editor
  example?: { in: string; out: string }; // sample I/O shown under the solver
}

export const INTERVIEW: Problem[] = [
  {
    id: "two-sum",
    list: "interview",
    category: "Arrays & Hashing",
    tag: "arrays · easy",
    title: "Two Sum",
    prompt: "// return indices of the two nums adding to target",
    description:
      "Given an array of integers nums and an integer target, return the indices of the two numbers such that they add up to target. You may assume there is exactly one valid answer, and you cannot use the same element twice.",
    example: { in: "nums = [2,7,11,15], target = 9", out: "[0, 1]" },
    solution: [
      "function twoSum(nums, target) {",
      "  const seen = new Map();              // value -> the index we saw it at",
      "  for (let i = 0; i < nums.length; i++) {",
      "    const need = target - nums[i];     // the partner that completes the pair",
      "    if (seen.has(need))                // already met it? we have our answer",
      "      return [seen.get(need), i];",
      "    seen.set(nums[i], i);              // remember this value for a later partner",
      "  }",
      "  return [];                           // the problem promises this is unreachable",
      "}",
      "// O(n) time, O(n) space - one pass, each Map lookup is O(1)",
    ],
    starter:
      "function twoSum(nums, target) {\n  // your code here\n}\n\nconsole.log(twoSum([2,7,11,15], 9)); // [0,1]",
  },
  {
    id: "max-subarray",
    list: "interview",
    category: "Dynamic Programming",
    tag: "dp · kadane",
    title: "Maximum Subarray",
    prompt: "// largest sum of a contiguous subarray",
    example: { in: "[-2,1,-3,4,-1,2,1,-5,4]", out: "6   // from [4,-1,2,1]" },
    solution: [
      "function maxSubArray(nums) {",
      "  let best = nums[0], cur = nums[0];   // both start on the first element",
      "  for (let i = 1; i < nums.length; i++) {",
      "    // extending only helps if the run so far is not dragging us down",
      "    cur = Math.max(nums[i], cur + nums[i]);",
      "    best = Math.max(best, cur);        // remember the best run ever seen",
      "  }",
      "  return best;",
      "}",
      "// Kadane's algorithm - O(n) time, O(1) space",
    ],
    starter:
      "function maxSubArray(nums) {\n  // your code here\n}\n\nconsole.log(maxSubArray([-2,1,-3,4,-1,2,1,-5,4])); // 6",
  },
  {
    id: "valid-parens",
    list: "interview",
    category: "Stack",
    tag: "stack · easy",
    title: "Valid Parentheses",
    prompt: "// is every bracket correctly closed?",
    example: { in: "\"()[]{}\"  ·  \"(]\"", out: "true  ·  false" },
    solution: [
      "function isValid(s) {",
      "  const pairs = { \")\": \"(\", \"]\": \"[\", \"}\": \"{\" };  // closer -> its opener",
      "  const stack = [];",
      "  for (const ch of s) {",
      "    if (!pairs[ch]) {                  // an opener: remember it for later",
      "      stack.push(ch);",
      "      continue;",
      "    }",
      "    // a closer must match the most recent unclosed opener",
      "    if (stack.pop() !== pairs[ch]) return false;",
      "  }",
      "  return stack.length === 0;           // anything still open is invalid",
      "}",
      "// O(n) time, O(n) space",
    ],
    starter:
      "function isValid(s) {\n  // your code here\n}\n\nconsole.log(isValid(\"()[]{}\")); // true",
  },
  {
    id: "lru",
    list: "interview",
    category: "Design",
    tag: "design · medium",
    title: "LRU Cache",
    prompt: "// O(1) get/put with eviction — Map keeps insertion order",
    example: {
      in: "cap 2: put(1,1) put(2,2) get(1) put(3,3) get(2)",
      out: "get(1) -> 1, get(2) -> -1  // 2 was evicted",
    },
    solution: [
      "class LRUCache {",
      "  constructor(cap) {",
      "    this.cap = cap;",
      "    this.m = new Map();                // Map preserves insertion order for us",
      "  }",
      "",
      "  get(k) {",
      "    if (!this.m.has(k)) return -1;     // miss",
      "    const v = this.m.get(k);",
      "    this.m.delete(k);                  // delete + re-set moves it to the end,",
      "    this.m.set(k, v);                  // which marks it most-recently-used",
      "    return v;",
      "  }",
      "",
      "  put(k, v) {",
      "    if (this.m.has(k)) this.m.delete(k);  // drop the old position first",
      "    this.m.set(k, v);                     // re-insert at the end = most recent",
      "    if (this.m.size > this.cap) {",
      "      // first key in insertion order is the least recently used",
      "      this.m.delete(this.m.keys().next().value);",
      "    }",
      "  }",
      "}",
      "// O(1) get and put - Map ordering does the bookkeeping",
    ],
    starter:
      "class LRUCache {\n  constructor(cap) {\n    // your code here\n  }\n\n  get(k) {\n    // your code here\n  }\n\n  put(k, v) {\n    // your code here\n  }\n}\n\nconst c = new LRUCache(2);\nc.put(1, 1);\nc.put(2, 2);\nconsole.log(c.get(1)); // 1",
  },
  {
    id: "rate-limiter",
    list: "interview",
    category: "Backend Design",
    tag: "backend · design",
    title: "Token Bucket Rate Limiter",
    prompt: "// allow N req/sec, refill over time — API gateway staple",
    example: {
      in: "new RateLimiter(2, 1000); allow() x3 instantly",
      out: "true, true, false  // 3rd waits for refill",
    },
    solution: [
      "class RateLimiter {",
      "  constructor(rate, per) {",
      "    this.rate = rate;                  // bucket size = the biggest burst allowed",
      "    this.per = per;                    // ms it takes to refill the whole bucket",
      "    this.tokens = rate;                // start full, so a burst works immediately",
      "    this.last = Date.now();",
      "  }",
      "",
      "  allow() {",
      "    const now = Date.now();",
      "    // refill continuously: elapsed/per is the fraction of a bucket earned",
      "    this.tokens += ((now - this.last) / this.per) * this.rate;",
      "    this.tokens = Math.min(this.tokens, this.rate);  // never over-fill",
      "    this.last = now;",
      "    if (this.tokens < 1) return false; // not even one whole token available",
      "    this.tokens -= 1;                  // spend one and let the call through",
      "    return true;",
      "  }",
      "}",
      "// O(1) time and memory - no request history is kept",
    ],
    starter:
      "class RateLimiter {\n  constructor(rate, per) {\n    // your code here\n  }\n\n  allow() {\n    // your code here\n  }\n}\n\nconst r = new RateLimiter(2, 1000);\nconsole.log([r.allow(), r.allow(), r.allow()]); // [true, true, false]",
  },
  {
    id: "debounce",
    list: "interview",
    category: "JavaScript",
    tag: "js · closures",
    title: "Implement debounce()",
    prompt: "// delay calls until input settles",
    example: {
      in: "const s = debounce(save, 300); 5 keystrokes fast",
      out: "save() runs once, 300ms after the last key",
    },
    solution: [
      "function debounce(fn, wait) {",
      "  let t;                               // the pending timer, if there is one",
      "  return function (...args) {",
      "    clearTimeout(t);                   // a new call cancels the queued one",
      "    // only the final call of a burst survives long enough to fire",
      "    t = setTimeout(() => fn.apply(this, args), wait);",
      "  };",
      "}",
      "// every call restarts the clock, so fn runs once the calls stop",
    ],
    starter:
      "function debounce(fn, wait) {\n  // your code here\n}\n\nlet n = 0;\nconst f = debounce(() => n++, 50);\nf();\nf();\nf();\nsetTimeout(() => console.log(n), 160); // 1",
  },
  {
    id: "binary-search",
    list: "interview",
    category: "Binary Search",
    tag: "search · easy",
    title: "Binary Search",
    prompt: "// find target index in a sorted array",
    example: { in: "[-1,0,3,5,9,12], target = 9", out: "4" },
    solution: [
      "function search(nums, target) {",
      "  let lo = 0, hi = nums.length - 1;    // inclusive bounds",
      "  while (lo <= hi) {",
      "    const mid = (lo + hi) >> 1;        // integer midpoint",
      "    if (nums[mid] === target) return mid;",
      "    if (nums[mid] < target) lo = mid + 1;   // answer must lie to the right",
      "    else hi = mid - 1;                      // answer must lie to the left",
      "  }",
      "  return -1;                           // bounds crossed - not present",
      "}",
      "// O(log n) - the search range halves every iteration",
    ],
    starter:
      "function search(nums, target) {\n  // your code here\n}\n\nconsole.log(search([-1,0,3,5,9,12], 9)); // 4",
  },
  {
    id: "promise-pool",
    list: "interview",
    category: "Async / Node",
    tag: "async · node",
    title: "Promise Pool (concurrency limit)",
    prompt: "// run tasks with max N in flight — batch job control",
    example: {
      in: "pool([t1..t6], 2)  // 6 jobs, limit 2",
      out: "results in order, never >2 running at once",
    },
    solution: [
      "async function pool(tasks, limit) {",
      "  const results = [];                  // indexed by position, not finish order",
      "  const running = new Set();           // the promises currently in flight",
      "  for (const [i, task] of tasks.entries()) {",
      "    const p = Promise.resolve(task()).then(r => { results[i] = r; });",
      "    running.add(p);",
      "    p.finally(() => running.delete(p));   // free the slot once it settles",
      "    // at the cap: wait for any one to finish before starting the next",
      "    if (running.size >= limit) await Promise.race(running);",
      "  }",
      "  await Promise.all(running);          // let the last few stragglers finish",
      "  return results;",
      "}",
      "// exactly `limit` run at once, and results keep their input order",
    ],
    starter:
      "async function pool(tasks, limit) {\n  // your code here\n}\n\npool([() => 1, () => Promise.resolve(2), () => 3], 2)\n  .then(r => console.log(r)); // [1, 2, 3]",
  },
  {
    id: "group-anagrams",
    list: "interview",
    category: "Arrays & Hashing",
    tag: "hashing · medium",
    title: "Group Anagrams",
    prompt: "// bucket words by sorted-letter key",
    example: {
      in: "['eat','tea','tan','ate','nat','bat']",
      out: "[['eat','tea','ate'], ['tan','nat'], ['bat']]",
    },
    solution: [
      "function groupAnagrams(strs) {",
      "  const groups = new Map();",
      "  for (const w of strs) {",
      "    // anagrams share the same letters, so sorted letters is a stable key",
      "    const key = w.split(\"\").sort().join(\"\");",
      "    if (!groups.has(key)) groups.set(key, []);",
      "    groups.get(key).push(w);           // every anagram lands in the same bucket",
      "  }",
      "  return [...groups.values()];",
      "}",
      "// O(n * k log k) for n words of length k",
    ],
    starter:
      "function groupAnagrams(strs) {\n  // your code here\n}\n\nconsole.log(groupAnagrams([\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]));",
  },
  {
    id: "flatten",
    list: "interview",
    category: "Recursion",
    tag: "recursion · js",
    title: "Flatten Nested Array",
    prompt: "// [1,[2,[3,[4]]]] -> [1,2,3,4]",
    example: { in: "[1,[2,[3,[4]]]]", out: "[1, 2, 3, 4]" },
    solution: [
      "function flatten(arr) {",
      "  return arr.reduce(",
      "    // recurse into nested arrays, keep every other value as it is",
      "    (out, x) => out.concat(Array.isArray(x) ? flatten(x) : x),",
      "    []                                 // start from an empty result",
      "  );",
      "}",
      "// or simply: arr.flat(Infinity)",
    ],
    starter:
      "function flatten(arr) {\n  // your code here\n}\n\nconsole.log(flatten([1,[2,[3,[4]]]])); // [1,2,3,4]",
  },
  {
    id: "longest-unique-substring",
    list: "interview",
    category: "Sliding Window",
    tag: "window · medium",
    title: "Longest Substring Without Repeating",
    prompt: "// length of the longest all-unique substring",
    example: { in: "\"abcabcbb\"  ·  \"bbbbb\"", out: "3 (\"abc\")  ·  1 (\"b\")" },
    solution: [
      "function lengthOfLongestSubstring(s) {",
      "  const seen = new Map();              // char -> the last index it appeared at",
      "  let best = 0, start = 0;             // start = left edge of the window",
      "  for (let i = 0; i < s.length; i++) {",
      "    const prev = seen.get(s[i]);",
      "    // only ever move the window forward, never back past `start`",
      "    if (prev !== undefined && prev >= start) start = prev + 1;",
      "    seen.set(s[i], i);",
      "    best = Math.max(best, i - start + 1);   // window size = i - start + 1",
      "  }",
      "  return best;",
      "}",
      "// sliding window - O(n), each character is handled once",
    ],
    starter:
      "function lengthOfLongestSubstring(s) {\n  // your code here\n}\n\nconsole.log(lengthOfLongestSubstring('abcabcbb')); // 3",
  },
  {
    id: "merge-intervals",
    list: "interview",
    category: "Intervals",
    tag: "sorting · medium",
    title: "Merge Intervals",
    prompt: "// collapse every overlapping range",
    example: { in: "[[1,3],[2,6],[8,10],[15,18]]", out: "[[1,6], [8,10], [15,18]]" },
    solution: [
      "function merge(intervals) {",
      "  intervals.sort((a, b) => a[0] - b[0]);  // sort by start so overlaps sit adjacent",
      "  const out = [];",
      "  for (const [s, e] of intervals) {",
      "    const last = out[out.length - 1];",
      "    // starts before the previous one ended -> they overlap, so stretch it",
      "    if (last && s <= last[1]) last[1] = Math.max(last[1], e);",
      "    else out.push([s, e]);             // no overlap: begin a new range",
      "  }",
      "  return out;",
      "}",
      "// O(n log n), dominated by the sort",
    ],
    starter:
      "function merge(intervals) {\n  // your code here\n}\n\nconsole.log(merge([[1,3],[2,6],[8,10]])); // [[1,6],[8,10]]",
  },
  {
    id: "reverse-list",
    list: "interview",
    category: "Linked List",
    tag: "pointers · easy",
    title: "Reverse Linked List",
    prompt: "// flip every next pointer in one pass",
    example: { in: "1 -> 2 -> 3 -> 4 -> null", out: "4 -> 3 -> 2 -> 1 -> null" },
    solution: [
      "function reverseList(head) {",
      "  let prev = null, cur = head;",
      "  while (cur) {",
      "    const next = cur.next;   // save the rest before we overwrite the link",
      "    cur.next = prev;         // point this node backwards",
      "    prev = cur;              // prev follows cur forward",
      "    cur = next;              // carry on down the original list",
      "  }",
      "  return prev;               // cur is null, so prev is the old tail = new head",
      "}",
      "// O(n) time, O(1) space - three pointers, no new nodes allocated",
    ],
    starter:
      "function reverseList(head) {\n  // your code here\n}\n\nconst node = (val, next = null) => ({ val, next });\nlet r = reverseList(node(1, node(2, node(3))));\nconst out = [];\nwhile (r) {\n  out.push(r.val);\n  r = r.next;\n}\nconsole.log(out); // [3, 2, 1]",
  },
  {
    id: "search-rotated",
    list: "interview",
    category: "Binary Search",
    tag: "search · medium",
    title: "Search in Rotated Sorted Array",
    prompt: "// binary search when the array is pivoted",
    example: { in: "[4,5,6,7,0,1,2], target = 0", out: "4" },
    solution: [
      "function searchRotated(nums, target) {",
      "  let lo = 0, hi = nums.length - 1;",
      "  while (lo <= hi) {",
      "    const mid = (lo + hi) >> 1;",
      "    if (nums[mid] === target) return mid;",
      "    // whatever the rotation, one side of mid is always properly sorted",
      "    if (nums[lo] <= nums[mid]) {            // left half is the sorted one",
      "      // inside that sorted range? search it. otherwise take the other half",
      "      if (nums[lo] <= target && target < nums[mid]) hi = mid - 1;",
      "      else lo = mid + 1;",
      "    } else {                                // right half is the sorted one",
      "      if (nums[mid] < target && target <= nums[hi]) lo = mid + 1;",
      "      else hi = mid - 1;",
      "    }",
      "  }",
      "  return -1;",
      "}",
      "// still O(log n) - one comparison decides which half to discard",
    ],
    starter:
      "function searchRotated(nums, target) {\n  // your code here\n}\n\nconsole.log(searchRotated([4,5,6,7,0,1,2], 0)); // 4",
  },
  {
    id: "num-islands-dfs",
    list: "interview",
    category: "Graphs",
    tag: "dfs · medium",
    title: "Number of Islands",
    prompt: "// count connected components of land",
    example: {
      in: "['11000',\n     '11000',\n     '00100']",
      out: "2   // two separate land masses",
    },
    solution: [
      "function numIslands(grid) {",
      "  let count = 0;",
      "  // flood fill: sink every cell of an island so it is only counted once",
      "  const sink = (r, c) => {",
      "    if (r < 0 || c < 0 || r >= grid.length) return;  // off the grid vertically",
      "    if (c >= grid[0].length) return;                 // off the right edge",
      "    if (grid[r][c] !== \"1\") return;                  // water, or already sunk",
      "    grid[r][c] = \"0\";                                // mark as visited",
      "    sink(r + 1, c); sink(r - 1, c);                  // spread vertically",
      "    sink(r, c + 1); sink(r, c - 1);                  // and horizontally",
      "  };",
      "  for (let r = 0; r < grid.length; r++)",
      "    for (let c = 0; c < grid[0].length; c++)",
      "      // each land cell still standing begins exactly one new island",
      "      if (grid[r][c] === \"1\") { count++; sink(r, c); }",
      "  return count;",
      "}",
      "// O(rows * cols) - every cell is looked at a constant number of times",
    ],
    starter:
      "function numIslands(grid) {\n  // your code here\n}\n\nconsole.log(numIslands([\n  [\"1\", \"1\", \"0\"],\n  [\"1\", \"1\", \"0\"],\n  [\"0\", \"0\", \"0\"],\n])); // 1",
  },
  {
    id: "top-k-frequent-bucket",
    list: "interview",
    category: "Arrays & Hashing",
    tag: "buckets · medium",
    title: "Top K Frequent Elements",
    prompt: "// k most common values, without a heap",
    example: { in: "nums = [1,1,1,2,2,3], k = 2", out: "[1, 2]" },
    solution: [
      "function topKFrequent(nums, k) {",
      "  const freq = new Map();",
      "  for (const n of nums)",
      "    freq.set(n, (freq.get(n) || 0) + 1);   // count how often each value appears",
      "  // buckets[i] holds every value seen exactly i times; i can never exceed n",
      "  const buckets = Array.from(",
      "    { length: nums.length + 1 }, () => []);",
      "  for (const [n, c] of freq) buckets[c].push(n);",
      "  const out = [];",
      "  // walk down from the highest possible count until we have k values",
      "  for (let c = buckets.length - 1; c >= 0; c--) {",
      "    if (out.length >= k) break;",
      "    out.push(...buckets[c]);",
      "  }",
      "  return out.slice(0, k);              // trim if the last bucket overshot k",
      "}",
      "// bucket sort - O(n), beats a heap's O(n log k) here",
    ],
    starter:
      "function topKFrequent(nums, k) {\n  // your code here\n}\n\nconsole.log(topKFrequent([1,1,1,2,2,3], 2)); // [1,2]",
  },
  {
    id: "climb-stairs-dp",
    list: "interview",
    category: "Dynamic Programming",
    tag: "dp · easy",
    title: "Climbing Stairs",
    prompt: "// ways to reach step n taking 1 or 2 at a time",
    example: { in: "n = 5", out: "8   // 1+1+1+1+1, 1+2+2, 2+1+2, ..." },
    solution: [
      "function climbStairs(n) {",
      "  // step n is reached from n-1 (one step) or n-2 (two), so the counts add",
      "  let a = 1, b = 1;                    // ways to stand at step 0 and step 1",
      "  for (let i = 2; i <= n; i++) {",
      "    [a, b] = [b, a + b];               // slide the two-value window forward",
      "  }",
      "  return b;",
      "}",
      "// Fibonacci in disguise - O(n) time, O(1) space",
    ],
    starter:
      "function climbStairs(n) {\n  // your code here\n}\n\nconsole.log(climbStairs(5)); // 8",
  },
  {
    id: "url-shortener",
    list: "interview",
    category: "Backend Design",
    tag: "backend · design",
    title: "URL Shortener",
    prompt: "// bit.ly in miniature — id -> short slug -> url",
    example: {
      in: "shorten('https://example.com/a/very/long/path')",
      out: "'sho.rt/b'  ->  expand() returns the original",
    },
    solution: [
      "const CHARS = 'abcdefghijklmnopqrstuvwxyz' +",
      "  'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';",
      "",
      "// turn a counter into a short slug - 62 symbols per character",
      "function base62(n) {",
      "  let s = '';",
      "  do {",
      "    s = CHARS[n % 62] + s;   // take the lowest base-62 digit, prepend it",
      "    n = Math.floor(n / 62);  // shift right by one digit",
      "  } while (n > 0);",
      "  return s;",
      "}",
      "",
      "class UrlShortener {",
      "  constructor() {",
      "    this.urls = new Map();   // slug -> the original url",
      "    this.next = 1;           // a counter, not a hash - so slugs never collide",
      "  }",
      "",
      "  shorten(url) {",
      "    const slug = base62(this.next++);  // consume one value from the counter",
      "    this.urls.set(slug, url);",
      "    return 'sho.rt/' + slug;",
      "  }",
      "",
      "  expand(short) {",
      "    // accept either a full short link or a bare slug",
      "    return this.urls.get(short.split('/').pop());",
      "  }",
      "}",
      "// 7 chars of base62 is about 3.5 trillion ids",
    ],
    starter:
      "class UrlShortener {\n  constructor() {\n    // your code here\n  }\n\n  shorten(url) {\n    // your code here\n  }\n\n  expand(short) {\n    // your code here\n  }\n}\n\nconst s = new UrlShortener();\nconst short = s.shorten(\"https://example.com\");\nconsole.log(short, s.expand(short));",
  },
  {
    id: "sliding-window-limiter",
    list: "interview",
    category: "Backend Design",
    tag: "backend · design",
    title: "Sliding Window Rate Limiter",
    prompt: "// exact per-key limit over a rolling window",
    example: {
      in: "limit 2 / 1000ms: allow('ip1') x3",
      out: "true, true, false  // 3rd is over the limit",
    },
    solution: [
      "class SlidingWindowLimiter {",
      "  constructor(limit, windowMs) {",
      "    this.limit = limit;",
      "    this.win = windowMs;",
      "    this.hits = new Map();      // key -> timestamps of that key's recent calls",
      "  }",
      "",
      "  allow(key) {",
      "    const now = Date.now();",
      "    // drop timestamps that aged out - this is what makes the window \"slide\"",
      "    const log = (this.hits.get(key) || [])",
      "      .filter(t => now - t < this.win);",
      "    this.hits.set(key, log);",
      "    if (log.length >= this.limit) return false;  // budget already spent",
      "    log.push(now);                               // record this call",
      "    return true;",
      "  }",
      "}",
      "// exact, but O(hits) memory - a token bucket scales better",
    ],
    starter:
      "class SlidingWindowLimiter {\n  constructor(limit, windowMs) {\n    // your code here\n  }\n\n  allow(key) {\n    // your code here\n  }\n}\n\nconst l = new SlidingWindowLimiter(2, 1000);\nconsole.log([l.allow(\"a\"), l.allow(\"a\"), l.allow(\"a\")]); // [true, true, false]",
  },
  {
    id: "throttle",
    list: "interview",
    category: "JavaScript",
    tag: "js · closures",
    title: "Implement throttle()",
    prompt: "// run at most once per interval — scroll handlers",
    example: {
      in: "throttle(onScroll, 200); scroll fires 60x/sec",
      out: "onScroll runs ~5x/sec, evenly spaced",
    },
    solution: [
      "function throttle(fn, wait) {",
      "  let last = 0, timer = null;  // when fn last ran, and any queued trailing call",
      "  return function (...args) {",
      "    const now = Date.now();",
      "    const left = wait - (now - last);  // ms until the window reopens",
      "    if (left <= 0) {          // window is open - fire straight away",
      "      last = now;",
      "      fn.apply(this, args);",
      "    } else if (!timer) {      // window closed - queue ONE trailing call",
      "      timer = setTimeout(() => {",
      "        last = Date.now();",
      "        timer = null;         // let the next burst queue again",
      "        fn.apply(this, args);",
      "      }, left);",
      "    }",
      "    // further calls while a timer is already pending are simply dropped",
      "  };",
      "}",
      "// leading + trailing edge: a burst produces exactly two calls",
    ],
    starter:
      "function throttle(fn, wait) {\n  // your code here\n}\n\nlet n = 0;\nconst f = throttle(() => n++, 80);\nf();\nf();\nf();\nsetTimeout(() => console.log(n), 220); // 2",
  },
];

export const NEETCODE_150: Problem[] = [
  ncStub("contains-duplicate", "Arrays & Hashing", "Contains Duplicate", "// return true if any value appears twice"),
  ncStub("valid-anagram", "Arrays & Hashing", "Valid Anagram", "// is t an anagram of s?"),
  ncStub("top-k-frequent", "Arrays & Hashing", "Top K Frequent Elements", "// k most frequent values"),
  ncStub("product-except-self", "Arrays & Hashing", "Product of Array Except Self", "// output[i] = product of all but nums[i]"),
  ncStub("valid-palindrome", "Two Pointers", "Valid Palindrome", "// alphanumeric, ignore case"),
  ncStub("three-sum", "Two Pointers", "3Sum", "// unique triplets summing to 0"),
  ncStub("container-water", "Two Pointers", "Container With Most Water", "// max area between two lines"),
  ncStub("best-time-stock", "Sliding Window", "Best Time to Buy/Sell Stock", "// max profit, one transaction"),
  ncStub("longest-substring", "Sliding Window", "Longest Substring Without Repeating", "// length of longest unique-char substring"),
  ncStub("min-window-substring", "Sliding Window", "Minimum Window Substring", "// smallest window containing all of t"),
  ncStub("num-islands", "Graphs", "Number of Islands", "// count connected land components"),
  ncStub("clone-graph", "Graphs", "Clone Graph", "// deep copy an adjacency graph"),
  ncStub("course-schedule", "Graphs", "Course Schedule", "// can all courses be finished? (cycle check)"),
  ncStub("climbing-stairs", "1-D DP", "Climbing Stairs", "// ways to reach step n (1 or 2 at a time)"),
  ncStub("coin-change", "1-D DP", "Coin Change", "// fewest coins to make amount"),
  ncStub("longest-inc-subseq", "1-D DP", "Longest Increasing Subsequence", "// length of LIS"),
  ncStub("invert-tree", "Trees", "Invert Binary Tree", "// mirror the tree"),
  ncStub("max-depth-tree", "Trees", "Maximum Depth of Binary Tree", "// height of the tree"),
  ncStub("same-tree", "Trees", "Same Tree", "// are two trees identical?"),
  ncStub("level-order", "Trees", "Binary Tree Level Order Traversal", "// BFS, level by level"),
];

function ncStub(id: string, category: string, title: string, prompt: string): Problem {
  return {
    id,
    list: "neetcode150",
    category,
    tag: `${category.toLowerCase()} · neetcode`,
    title,
    prompt,
    solution: [], // fill in later; empty => "coming soon"
    starter: `// ${title}\n// ${prompt}\n\nfunction solve() {\n  // your code here\n}\n`,
  };
}

// the live IDE only cycles problems that actually have a solution
export const SOLVED_FOR_MONITOR = INTERVIEW.filter((p) => p.solution.length > 0);
