// Problems power both the ambient monitor solver AND the Code Lab.
// `list` lets the UI filter (interview / neetcode150). Add NeetCode 150
// entries over time by pushing to NEETCODE_150 below.

export interface Problem {
  id: string;
  list: "interview" | "neetcode150";
  category: string;    // e.g. "Arrays & Hashing"
  tag: string;         // difficulty / flavor
  title: string;
  prompt: string;      // short statement
  solution: string[];  // commented JS solution, line by line
  starter?: string;    // starter code for the Code Lab editor
  example?: { in: string; out: string }; // sample I/O shown under the solver
}

export const INTERVIEW: Problem[] = [
  {
    id: "two-sum",
    list: "interview",
    category: "Arrays & Hashing",
    tag: "arrays · easy",
    title: "Two Sum",
    prompt: "// return indices of the two nums adding to target",
    example: { in: "nums = [2,7,11,15], target = 9", out: "[0, 1]" },
    solution: [
      "function twoSum(nums, target) {",
      "  // map remembers each value -> its index as we go",
      "  const seen = new Map();",
      "  for (let i = 0; i < nums.length; i++) {",
      "    const need = target - nums[i];      // what pairs with nums[i]",
      "    if (seen.has(need)) return [seen.get(need), i];",
      "    seen.set(nums[i], i);",
      "  }",
      "  return [];",
      "}",
      "// O(n) time, O(n) space",
    ],
    starter:
      "function twoSum(nums, target) {\n  // your code here\n}\n\nconsole.log(twoSum([2,7,11,15], 9)); // [0,1]",
  },
  {
    id: "max-subarray",
    list: "interview",
    category: "Dynamic Programming",
    tag: "dp · kadane",
    title: "Maximum Subarray",
    prompt: "// largest sum of a contiguous subarray",
    example: { in: "[-2,1,-3,4,-1,2,1,-5,4]", out: "6   // from [4,-1,2,1]" },
    solution: [
      "function maxSubArray(nums) {",
      "  let best = nums[0], cur = nums[0];",
      "  for (let i = 1; i < nums.length; i++) {",
      "    // either extend the run, or start fresh at nums[i]",
      "    cur = Math.max(nums[i], cur + nums[i]);",
      "    best = Math.max(best, cur);",
      "  }",
      "  return best;",
      "}",
      "// Kadane's algorithm — O(n)",
    ],
    starter:
      "function maxSubArray(nums) {\n  // your code here\n}\n\nconsole.log(maxSubArray([-2,1,-3,4,-1,2,1,-5,4])); // 6",
  },
  {
    id: "valid-parens",
    list: "interview",
    category: "Stack",
    tag: "stack · easy",
    title: "Valid Parentheses",
    prompt: "// is every bracket correctly closed?",
    example: { in: "\"()[]{}\"  ·  \"(]\"", out: "true  ·  false" },
    solution: [
      "function isValid(s) {",
      "  const stack = [], map = { ')':'(', ']':'[', '}':'{' };",
      "  for (const ch of s) {",
      "    if (!map[ch]) { stack.push(ch); continue; }  // opener",
      "    if (stack.pop() !== map[ch]) return false;    // mismatch",
      "  }",
      "  return stack.length === 0;",
      "}",
      "// O(n)",
    ],
    starter:
      "function isValid(s) {\n  // your code here\n}\n\nconsole.log(isValid(\"()[]{}\")); // true",
  },
  {
    id: "lru",
    list: "interview",
    category: "Design",
    tag: "design · medium",
    title: "LRU Cache",
    prompt: "// O(1) get/put with eviction — Map keeps insertion order",
    example: {
      in: "cap 2: put(1,1) put(2,2) get(1) put(3,3) get(2)",
      out: "get(1) -> 1, get(2) -> -1  // 2 was evicted",
    },
    solution: [
      "class LRUCache {",
      "  constructor(cap) { this.cap = cap; this.m = new Map(); }",
      "  get(k) {",
      "    if (!this.m.has(k)) return -1;",
      "    const v = this.m.get(k);",
      "    this.m.delete(k); this.m.set(k, v);  // mark as most-recent",
      "    return v;",
      "  }",
      "  put(k, v) {",
      "    if (this.m.has(k)) this.m.delete(k);",
      "    this.m.set(k, v);",
      "    if (this.m.size > this.cap)          // evict least-recent",
      "      this.m.delete(this.m.keys().next().value);",
      "  }",
      "}",
      "// O(1) get and put",
    ],
  },
  {
    id: "rate-limiter",
    list: "interview",
    category: "Backend Design",
    tag: "backend · design",
    title: "Token Bucket Rate Limiter",
    prompt: "// allow N req/sec, refill over time — API gateway staple",
    example: {
      in: "new RateLimiter(2, 1000); allow() x3 instantly",
      out: "true, true, false  // 3rd waits for refill",
    },
    solution: [
      "class RateLimiter {",
      "  constructor(rate, per) {",
      "    this.rate = rate; this.per = per;",
      "    this.tokens = rate; this.last = Date.now();",
      "  }",
      "  allow() {",
      "    const now = Date.now();",
      "    // refill proportionally to time elapsed",
      "    this.tokens += ((now - this.last) / this.per) * this.rate;",
      "    this.tokens = Math.min(this.tokens, this.rate);",
      "    this.last = now;",
      "    if (this.tokens < 1) return false;",
      "    this.tokens -= 1; return true;",
      "  }",
      "}",
    ],
  },
  {
    id: "debounce",
    list: "interview",
    category: "JavaScript",
    tag: "js · closures",
    title: "Implement debounce()",
    prompt: "// delay calls until input settles",
    example: {
      in: "const s = debounce(save, 300); 5 keystrokes fast",
      out: "save() runs once, 300ms after the last key",
    },
    solution: [
      "function debounce(fn, wait) {",
      "  let t;",
      "  return function (...args) {",
      "    clearTimeout(t);                       // cancel pending call",
      "    t = setTimeout(() => fn.apply(this, args), wait);",
      "  };",
      "}",
    ],
  },
  {
    id: "binary-search",
    list: "interview",
    category: "Binary Search",
    tag: "search · easy",
    title: "Binary Search",
    prompt: "// find target index in a sorted array",
    example: { in: "[-1,0,3,5,9,12], target = 9", out: "4" },
    solution: [
      "function search(nums, target) {",
      "  let lo = 0, hi = nums.length - 1;",
      "  while (lo <= hi) {",
      "    const mid = (lo + hi) >> 1;            // floor midpoint",
      "    if (nums[mid] === target) return mid;",
      "    if (nums[mid] < target) lo = mid + 1;",
      "    else hi = mid - 1;",
      "  }",
      "  return -1;",
      "}",
      "// O(log n)",
    ],
    starter:
      "function search(nums, target) {\n  // your code here\n}\n\nconsole.log(search([-1,0,3,5,9,12], 9)); // 4",
  },
  {
    id: "promise-pool",
    list: "interview",
    category: "Async / Node",
    tag: "async · node",
    title: "Promise Pool (concurrency limit)",
    prompt: "// run tasks with max N in flight — batch job control",
    example: {
      in: "pool([t1..t6], 2)  // 6 jobs, limit 2",
      out: "results in order, never >2 running at once",
    },
    solution: [
      "async function pool(tasks, limit) {",
      "  const results = []; const running = new Set();",
      "  for (const [i, task] of tasks.entries()) {",
      "    const p = Promise.resolve(task()).then(r => results[i] = r);",
      "    running.add(p);",
      "    p.finally(() => running.delete(p));",
      "    if (running.size >= limit) await Promise.race(running);",
      "  }",
      "  await Promise.all(running);",
      "  return results;",
      "}",
    ],
  },
  {
    id: "group-anagrams",
    list: "interview",
    category: "Arrays & Hashing",
    tag: "hashing · medium",
    title: "Group Anagrams",
    prompt: "// bucket words by sorted-letter key",
    example: {
      in: "['eat','tea','tan','ate','nat','bat']",
      out: "[['eat','tea','ate'], ['tan','nat'], ['bat']]",
    },
    solution: [
      "function groupAnagrams(strs) {",
      "  const map = new Map();",
      "  for (const s of strs) {",
      "    const key = [...s].sort().join('');   // anagrams share this",
      "    map.set(key, [...(map.get(key) || []), s]);",
      "  }",
      "  return [...map.values()];",
      "}",
      "// O(n·k log k)",
    ],
  },
  {
    id: "flatten",
    list: "interview",
    category: "Recursion",
    tag: "recursion · js",
    title: "Flatten Nested Array",
    prompt: "// [1,[2,[3,[4]]]] -> [1,2,3,4]",
    example: { in: "[1,[2,[3,[4]]]]", out: "[1, 2, 3, 4]" },
    solution: [
      "function flatten(arr) {",
      "  return arr.reduce((out, x) =>",
      "    out.concat(Array.isArray(x) ? flatten(x) : x), []);",
      "}",
      "// or simply: arr.flat(Infinity)",
    ],
    starter:
      "function flatten(arr) {\n  // your code here\n}\n\nconsole.log(flatten([1,[2,[3,[4]]]])); // [1,2,3,4]",
  },
  {
    id: "longest-unique-substring",
    list: "interview",
    category: "Sliding Window",
    tag: "window · medium",
    title: "Longest Substring Without Repeating",
    prompt: "// length of the longest all-unique substring",
    example: { in: "\"abcabcbb\"  ·  \"bbbbb\"", out: "3 (\"abc\")  ·  1 (\"b\")" },
    solution: [
      "function lengthOfLongestSubstring(s) {",
      "  const seen = new Map();   // char -> last index seen",
      "  let best = 0, start = 0;",
      "  for (let i = 0; i < s.length; i++) {",
      "    const prev = seen.get(s[i]);",
      "    // only ever move the window forward, never back",
      "    if (prev >= start) start = prev + 1;",
      "    seen.set(s[i], i);",
      "    best = Math.max(best, i - start + 1);",
      "  }",
      "  return best;",
      "}",
      "// sliding window — O(n)",
    ],
    starter:
      "function lengthOfLongestSubstring(s) {\n  // your code here\n}\n\nconsole.log(lengthOfLongestSubstring('abcabcbb')); // 3",
  },
  {
    id: "merge-intervals",
    list: "interview",
    category: "Intervals",
    tag: "sorting · medium",
    title: "Merge Intervals",
    prompt: "// collapse every overlapping range",
    example: { in: "[[1,3],[2,6],[8,10],[15,18]]", out: "[[1,6], [8,10], [15,18]]" },
    solution: [
      "function merge(intervals) {",
      "  intervals.sort((a, b) => a[0] - b[0]);",
      "  const out = [];",
      "  for (const [s, e] of intervals) {",
      "    const last = out[out.length - 1];",
      "    // overlaps the previous range -> stretch it",
      "    if (last && s <= last[1])",
      "      last[1] = Math.max(last[1], e);",
      "    else out.push([s, e]);",
      "  }",
      "  return out;",
      "}",
      "// O(n log n), dominated by the sort",
    ],
    starter:
      "function merge(intervals) {\n  // your code here\n}\n\nconsole.log(merge([[1,3],[2,6],[8,10]])); // [[1,6],[8,10]]",
  },
  {
    id: "reverse-list",
    list: "interview",
    category: "Linked List",
    tag: "pointers · easy",
    title: "Reverse Linked List",
    prompt: "// flip every next pointer in one pass",
    example: { in: "1 -> 2 -> 3 -> 4 -> null", out: "4 -> 3 -> 2 -> 1 -> null" },
    solution: [
      "function reverseList(head) {",
      "  let prev = null, cur = head;",
      "  while (cur) {",
      "    const next = cur.next;   // hold the rest of the list",
      "    cur.next = prev;         // flip this link",
      "    prev = cur;",
      "    cur = next;",
      "  }",
      "  return prev;               // prev is the new head",
      "}",
      "// O(n) time, O(1) space",
    ],
  },
  {
    id: "search-rotated",
    list: "interview",
    category: "Binary Search",
    tag: "search · medium",
    title: "Search in Rotated Sorted Array",
    prompt: "// binary search when the array is pivoted",
    example: { in: "[4,5,6,7,0,1,2], target = 0", out: "4" },
    solution: [
      "function searchRotated(nums, target) {",
      "  let lo = 0, hi = nums.length - 1;",
      "  while (lo <= hi) {",
      "    const mid = (lo + hi) >> 1;",
      "    if (nums[mid] === target) return mid;",
      "    // one side of mid is always properly sorted",
      "    if (nums[lo] <= nums[mid]) {",
      "      if (target >= nums[lo] && target < nums[mid])",
      "        hi = mid - 1;",
      "      else lo = mid + 1;",
      "    } else {",
      "      if (target > nums[mid] && target <= nums[hi])",
      "        lo = mid + 1;",
      "      else hi = mid - 1;",
      "    }",
      "  }",
      "  return -1;",
      "}",
      "// still O(log n)",
    ],
    starter:
      "function searchRotated(nums, target) {\n  // your code here\n}\n\nconsole.log(searchRotated([4,5,6,7,0,1,2], 0)); // 4",
  },
  {
    id: "num-islands-dfs",
    list: "interview",
    category: "Graphs",
    tag: "dfs · medium",
    title: "Number of Islands",
    prompt: "// count connected components of land",
    example: {
      in: "['11000',\n     '11000',\n     '00100']",
      out: "2   // two separate land masses",
    },
    solution: [
      "function numIslands(grid) {",
      "  let count = 0;",
      "  const sink = (r, c) => {",
      "    if (r < 0 || c < 0 || r >= grid.length) return;",
      "    if (c >= grid[0].length) return;",
      "    if (grid[r][c] !== '1') return;",
      "    grid[r][c] = '0';        // mark as visited",
      "    sink(r + 1, c); sink(r - 1, c);",
      "    sink(r, c + 1); sink(r, c - 1);",
      "  };",
      "  for (let r = 0; r < grid.length; r++)",
      "    for (let c = 0; c < grid[0].length; c++)",
      "      if (grid[r][c] === '1') { count++; sink(r, c); }",
      "  return count;",
      "}",
      "// flood fill — O(rows · cols)",
    ],
  },
  {
    id: "top-k-frequent-bucket",
    list: "interview",
    category: "Arrays & Hashing",
    tag: "buckets · medium",
    title: "Top K Frequent Elements",
    prompt: "// k most common values, without a heap",
    example: { in: "nums = [1,1,1,2,2,3], k = 2", out: "[1, 2]" },
    solution: [
      "function topKFrequent(nums, k) {",
      "  const freq = new Map();",
      "  for (const n of nums)",
      "    freq.set(n, (freq.get(n) || 0) + 1);",
      "  // buckets[i] holds every value seen exactly i times",
      "  const buckets = Array.from(",
      "    { length: nums.length + 1 }, () => []);",
      "  for (const [n, c] of freq) buckets[c].push(n);",
      "  const out = [];",
      "  for (let c = buckets.length - 1; c >= 0; c--) {",
      "    if (out.length >= k) break;",
      "    out.push(...buckets[c]);",
      "  }",
      "  return out.slice(0, k);",
      "}",
      "// bucket sort — O(n), beats a heap here",
    ],
    starter:
      "function topKFrequent(nums, k) {\n  // your code here\n}\n\nconsole.log(topKFrequent([1,1,1,2,2,3], 2)); // [1,2]",
  },
  {
    id: "climb-stairs-dp",
    list: "interview",
    category: "Dynamic Programming",
    tag: "dp · easy",
    title: "Climbing Stairs",
    prompt: "// ways to reach step n taking 1 or 2 at a time",
    example: { in: "n = 5", out: "8   // 1+1+1+1+1, 1+2+2, 2+1+2, ..." },
    solution: [
      "function climbStairs(n) {",
      "  let a = 1, b = 1;   // ways to reach n-2 and n-1",
      "  for (let i = 2; i <= n; i++) {",
      "    [a, b] = [b, a + b];",
      "  }",
      "  return b;",
      "}",
      "// Fibonacci in disguise — O(n) time, O(1) space",
    ],
    starter:
      "function climbStairs(n) {\n  // your code here\n}\n\nconsole.log(climbStairs(5)); // 8",
  },
  {
    id: "url-shortener",
    list: "interview",
    category: "Backend Design",
    tag: "backend · design",
    title: "URL Shortener",
    prompt: "// bit.ly in miniature — id -> short slug -> url",
    example: {
      in: "shorten('https://example.com/a/very/long/path')",
      out: "'sho.rt/b'  ->  expand() returns the original",
    },
    solution: [
      "const CHARS = 'abcdefghijklmnopqrstuvwxyz' +",
      "  'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';",
      "",
      "class UrlShortener {",
      "  constructor() { this.urls = new Map(); this.next = 1; }",
      "  shorten(url) {",
      "    // a counter, not a hash — so slugs never collide",
      "    const slug = base62(this.next++);",
      "    this.urls.set(slug, url);",
      "    return 'sho.rt/' + slug;",
      "  }",
      "  expand(short) {",
      "    return this.urls.get(short.split('/').pop());",
      "  }",
      "}",
      "",
      "function base62(n) {",
      "  let s = '';",
      "  do {",
      "    s = CHARS[n % 62] + s;",
      "    n = Math.floor(n / 62);",
      "  } while (n > 0);",
      "  return s;",
      "}",
      "// 7 chars of base62 ≈ 3.5 trillion ids",
    ],
  },
  {
    id: "sliding-window-limiter",
    list: "interview",
    category: "Backend Design",
    tag: "backend · design",
    title: "Sliding Window Rate Limiter",
    prompt: "// exact per-key limit over a rolling window",
    example: {
      in: "limit 2 / 1000ms: allow('ip1') x3",
      out: "true, true, false  // 3rd is over the limit",
    },
    solution: [
      "class SlidingWindowLimiter {",
      "  constructor(limit, windowMs) {",
      "    this.limit = limit;",
      "    this.win = windowMs;",
      "    this.hits = new Map();      // key -> timestamps",
      "  }",
      "  allow(key) {",
      "    const now = Date.now();",
      "    // drop anything that fell out of the window",
      "    const log = (this.hits.get(key) || [])",
      "      .filter(t => now - t < this.win);",
      "    this.hits.set(key, log);",
      "    if (log.length >= this.limit) return false;",
      "    log.push(now);",
      "    return true;",
      "  }",
      "}",
      "// exact, but O(hits) memory — token bucket scales better",
    ],
  },
  {
    id: "throttle",
    list: "interview",
    category: "JavaScript",
    tag: "js · closures",
    title: "Implement throttle()",
    prompt: "// run at most once per interval — scroll handlers",
    example: {
      in: "throttle(onScroll, 200); scroll fires 60x/sec",
      out: "onScroll runs ~5x/sec, evenly spaced",
    },
    solution: [
      "function throttle(fn, wait) {",
      "  let last = 0, timer = null;",
      "  return function (...args) {",
      "    const now = Date.now();",
      "    const left = wait - (now - last);",
      "    if (left <= 0) {          // window open — fire now",
      "      last = now;",
      "      fn.apply(this, args);",
      "    } else if (!timer) {      // queue the trailing call",
      "      timer = setTimeout(() => {",
      "        last = Date.now();",
      "        timer = null;",
      "        fn.apply(this, args);",
      "      }, left);",
      "    }",
      "  };",
      "}",
    ],
  },
];

// ---- NeetCode 150: full list scaffold, fill `solution` over time ----
// Only entries with a non-empty `solution` show a solution; others show
// "solution coming soon" but are still selectable & runnable in the Lab.
export const NEETCODE_150: Problem[] = [
  ncStub("contains-duplicate", "Arrays & Hashing", "Contains Duplicate", "// return true if any value appears twice"),
  ncStub("valid-anagram", "Arrays & Hashing", "Valid Anagram", "// is t an anagram of s?"),
  ncStub("top-k-frequent", "Arrays & Hashing", "Top K Frequent Elements", "// k most frequent values"),
  ncStub("product-except-self", "Arrays & Hashing", "Product of Array Except Self", "// output[i] = product of all but nums[i]"),
  ncStub("valid-palindrome", "Two Pointers", "Valid Palindrome", "// alphanumeric, ignore case"),
  ncStub("three-sum", "Two Pointers", "3Sum", "// unique triplets summing to 0"),
  ncStub("container-water", "Two Pointers", "Container With Most Water", "// max area between two lines"),
  ncStub("best-time-stock", "Sliding Window", "Best Time to Buy/Sell Stock", "// max profit, one transaction"),
  ncStub("longest-substring", "Sliding Window", "Longest Substring Without Repeating", "// length of longest unique-char substring"),
  ncStub("min-window-substring", "Sliding Window", "Minimum Window Substring", "// smallest window containing all of t"),
  ncStub("num-islands", "Graphs", "Number of Islands", "// count connected land components"),
  ncStub("clone-graph", "Graphs", "Clone Graph", "// deep copy an adjacency graph"),
  ncStub("course-schedule", "Graphs", "Course Schedule", "// can all courses be finished? (cycle check)"),
  ncStub("climbing-stairs", "1-D DP", "Climbing Stairs", "// ways to reach step n (1 or 2 at a time)"),
  ncStub("coin-change", "1-D DP", "Coin Change", "// fewest coins to make amount"),
  ncStub("longest-inc-subseq", "1-D DP", "Longest Increasing Subsequence", "// length of LIS"),
  ncStub("invert-tree", "Trees", "Invert Binary Tree", "// mirror the tree"),
  ncStub("max-depth-tree", "Trees", "Maximum Depth of Binary Tree", "// height of the tree"),
  ncStub("same-tree", "Trees", "Same Tree", "// are two trees identical?"),
  ncStub("level-order", "Trees", "Binary Tree Level Order Traversal", "// BFS, level by level"),
];

function ncStub(id: string, category: string, title: string, prompt: string): Problem {
  return {
    id,
    list: "neetcode150",
    category,
    tag: `${category.toLowerCase()} · neetcode`,
    title,
    prompt,
    solution: [], // fill in later; empty => "coming soon"
    starter: `// ${title}\n// ${prompt}\n\nfunction solve() {\n  // your code here\n}\n`,
  };
}

// the live IDE only cycles problems that actually have a solution
export const SOLVED_FOR_MONITOR = INTERVIEW.filter((p) => p.solution.length > 0);
