import type { LangTable } from "./index";

export const CPP: LangTable = {
  "two-sum": {
    starter: "#include <iostream>\n#include <vector>\n#include <unordered_map>\n\nstd::vector<int> twoSum(const std::vector<int>& nums, int target) {\n    // your code here\n    return {};\n}\n\nint main() {\n    for (int i : twoSum({2, 7, 11, 15}, 9)) std::cout << i << \" \";\n    std::cout << std::endl;  // 0 1\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "#include <unordered_map>",
      "",
      "std::vector<int> twoSum(const std::vector<int>& nums, int target) {",
      "    std::unordered_map<int, int> seen;              // value -> its index",
      "    for (int i = 0; i < (int)nums.size(); i++) {",
      "        int need = target - nums[i];                // the partner we want",
      "        auto it = seen.find(need);",
      "        if (it != seen.end()) return {it->second, i};  // met it already",
      "        seen[nums[i]] = i;                          // remember for later",
      "    }",
      "    return {};                                      // promised unreachable",
      "}",
      "",
      "int main() {",
      "    for (int i : twoSum({2, 7, 11, 15}, 9)) std::cout << i << \" \";",
      "    std::cout << std::endl;",
      "    return 0;",
      "}",
      "// O(n) time, O(n) space - one pass, O(1) average lookups",
    ],
    expectedOutput: "0 1",
  },

  "max-subarray": {
    starter: "#include <iostream>\n#include <vector>\n#include <algorithm>\n\nint maxSubArray(const std::vector<int>& nums) {\n    // your code here\n    return 0;\n}\n\nint main() {\n    std::cout << maxSubArray({-2, 1, -3, 4, -1, 2, 1, -5, 4}) << std::endl;  // 6\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "#include <algorithm>",
      "",
      "int maxSubArray(const std::vector<int>& nums) {",
      "    int best = nums[0], cur = nums[0];        // both start on element 0",
      "    for (int i = 1; i < (int)nums.size(); i++) {",
      "        // extending only helps if the run so far is not dragging us down",
      "        cur = std::max(nums[i], cur + nums[i]);",
      "        best = std::max(best, cur);           // remember the best run seen",
      "    }",
      "    return best;",
      "}",
      "",
      "int main() {",
      "    std::cout << maxSubArray({-2, 1, -3, 4, -1, 2, 1, -5, 4}) << std::endl;",
      "    return 0;",
      "}",
      "// Kadane's algorithm - O(n) time, O(1) space",
    ],
    expectedOutput: "6",
  },

  "valid-parens": {
    starter: "#include <iostream>\n#include <string>\n#include <stack>\n#include <unordered_map>\n\nbool isValid(const std::string& s) {\n    // your code here\n    return false;\n}\n\nint main() {\n    std::cout << (isValid(\"()[]{}\") ? \"true\" : \"false\") << std::endl;  // true\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <string>",
      "#include <stack>",
      "#include <unordered_map>",
      "",
      "bool isValid(const std::string& s) {",
      "    std::unordered_map<char, char> pairs{",
      "        {')', '('}, {']', '['}, {'}', '{'}};   // closer -> its opener",
      "    std::stack<char> st;",
      "    for (char ch : s) {",
      "        auto it = pairs.find(ch);",
      "        if (it == pairs.end()) {               // an opener: remember it",
      "            st.push(ch);",
      "            continue;",
      "        }",
      "        // a closer must match the most recent unclosed opener",
      "        if (st.empty() || st.top() != it->second) return false;",
      "        st.pop();",
      "    }",
      "    return st.empty();                         // anything left open is invalid",
      "}",
      "",
      "int main() {",
      "    std::cout << (isValid(\"()[]{}\") ? \"true\" : \"false\") << std::endl;",
      "    return 0;",
      "}",
      "// O(n) time, O(n) space",
    ],
    expectedOutput: "true",
  },

  "lru": {
    starter: "#include <iostream>\n#include <list>\n#include <unordered_map>\n\nclass LRUCache {\npublic:\n    LRUCache(int cap) {\n        // your code here\n    }\n\n    int get(int k) {\n        // your code here\n        return -1;\n    }\n\n    void put(int k, int v) {\n        // your code here\n    }\n};\n\nint main() {\n    LRUCache c(2);\n    c.put(1, 1);\n    c.put(2, 2);\n    std::cout << c.get(1) << std::endl;  // 1\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <list>",
      "#include <unordered_map>",
      "",
      "class LRUCache {",
      "public:",
      "    LRUCache(int cap) : cap_(cap) {}",
      "",
      "    int get(int k) {",
      "        auto it = pos_.find(k);",
      "        if (it == pos_.end()) return -1;            // miss",
      "        // splice moves the node to the front in O(1) without reallocating",
      "        order_.splice(order_.begin(), order_, it->second);",
      "        return it->second->second;",
      "    }",
      "",
      "    void put(int k, int v) {",
      "        auto it = pos_.find(k);",
      "        if (it != pos_.end()) {                     // already present: refresh",
      "            it->second->second = v;",
      "            order_.splice(order_.begin(), order_, it->second);",
      "            return;",
      "        }",
      "        order_.emplace_front(k, v);                 // newest at the front",
      "        pos_[k] = order_.begin();",
      "        if ((int)order_.size() > cap_) {",
      "            pos_.erase(order_.back().first);        // back = least recently used",
      "            order_.pop_back();",
      "        }",
      "    }",
      "",
      "private:",
      "    int cap_;",
      "    std::list<std::pair<int, int>> order_;                                  // MRU -> LRU",
      "    std::unordered_map<int, std::list<std::pair<int, int>>::iterator> pos_; // key -> node",
      "};",
      "",
      "int main() {",
      "    LRUCache c(2);",
      "    c.put(1, 1);",
      "    c.put(2, 2);",
      "    std::cout << c.get(1) << std::endl;",
      "    c.put(3, 3);",
      "    std::cout << c.get(2) << std::endl;",
      "    return 0;",
      "}",
      "// O(1) get and put - a list for order, a hash map for lookup",
    ],
    expectedOutput: "1\n-1",
  },

  "rate-limiter": {
    starter: "#include <iostream>\n#include <chrono>\n#include <algorithm>\n\nclass RateLimiter {\npublic:\n    RateLimiter(double rate, double per) {\n        // your code here\n    }\n\n    bool allow() {\n        // your code here\n        return false;\n    }\n};\n\nint main() {\n    RateLimiter r(2, 1000);\n    std::cout << r.allow() << \" \" << r.allow() << \" \" << r.allow() << std::endl;\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <chrono>",
      "#include <algorithm>",
      "",
      "static long nowMs() {",
      "    using namespace std::chrono;",
      "    return duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count();",
      "}",
      "",
      "class RateLimiter {",
      "public:",
      "    RateLimiter(double rate, double per)",
      "        : rate_(rate), per_(per), tokens_(rate), last_(nowMs()) {}",
      "        // bucket starts full, so a burst up to `rate` works immediately",
      "",
      "    bool allow() {",
      "        long now = nowMs();",
      "        // refill continuously: elapsed/per is the fraction of a bucket earned",
      "        tokens_ += ((now - last_) / per_) * rate_;",
      "        tokens_ = std::min(tokens_, rate_);   // never over-fill",
      "        last_ = now;",
      "        if (tokens_ < 1) return false;        // not even one whole token",
      "        tokens_ -= 1;                         // spend it",
      "        return true;",
      "    }",
      "",
      "private:",
      "    double rate_, per_, tokens_;",
      "    long last_;",
      "};",
      "",
      "int main() {",
      "    RateLimiter r(2, 1000);",
      "    std::cout << r.allow() << \" \" << r.allow() << \" \" << r.allow() << std::endl;",
      "    return 0;",
      "}",
      "// O(1) time and memory - no request history is kept",
    ],
    expectedOutput: "1 1 0",
  },

  "debounce": {
    starter: "#include <iostream>\n#include <functional>\n#include <thread>\n#include <chrono>\n#include <atomic>\n\nclass Debouncer {\npublic:\n    Debouncer(int waitMs) {\n        // your code here\n    }\n\n    void call(std::function<void()> fn) {\n        // your code here\n    }\n};\n\nint main() {\n    std::atomic<int> n{0};\n    Debouncer d(50);\n    d.call([&] { n++; });\n    d.call([&] { n++; });\n    std::this_thread::sleep_for(std::chrono::milliseconds(200));\n    std::cout << n.load() << std::endl;  // 1\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <functional>",
      "#include <thread>",
      "#include <chrono>",
      "#include <atomic>",
      "#include <mutex>",
      "",
      "class Debouncer {",
      "public:",
      "    explicit Debouncer(int waitMs) : waitMs_(waitMs) {}",
      "",
      "    void call(std::function<void()> fn) {",
      "        std::lock_guard<std::mutex> lock(m_);",
      "        int myGen = ++gen_;          // each call invalidates the previous one",
      "        std::thread([this, fn, myGen] {",
      "            std::this_thread::sleep_for(std::chrono::milliseconds(waitMs_));",
      "            std::lock_guard<std::mutex> lock(m_);",
      "            // only fire if no newer call arrived while we were sleeping",
      "            if (myGen == gen_) fn();",
      "        }).detach();",
      "    }",
      "",
      "private:",
      "    int waitMs_;",
      "    int gen_ = 0;                    // generation counter stands in for a timer id",
      "    std::mutex m_;",
      "};",
      "",
      "int main() {",
      "    std::atomic<int> n{0};",
      "    Debouncer d(50);",
      "    d.call([&] { n++; });",
      "    d.call([&] { n++; });",
      "    d.call([&] { n++; });",
      "    std::this_thread::sleep_for(std::chrono::milliseconds(200));",
      "    std::cout << n.load() << std::endl;",
      "    return 0;",
      "}",
      "// every call bumps the generation, so only the last one survives",
    ],
    expectedOutput: "1",
  },

  "binary-search": {
    starter: "#include <iostream>\n#include <vector>\n\nint search(const std::vector<int>& nums, int target) {\n    // your code here\n    return -1;\n}\n\nint main() {\n    std::cout << search({-1, 0, 3, 5, 9, 12}, 9) << std::endl;  // 4\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "",
      "int search(const std::vector<int>& nums, int target) {",
      "    int lo = 0, hi = (int)nums.size() - 1;    // inclusive bounds",
      "    while (lo <= hi) {",
      "        int mid = lo + (hi - lo) / 2;         // written this way to avoid overflow",
      "        if (nums[mid] == target) return mid;",
      "        if (nums[mid] < target) lo = mid + 1; // answer lies to the right",
      "        else hi = mid - 1;                    // answer lies to the left",
      "    }",
      "    return -1;                                // bounds crossed - not present",
      "}",
      "",
      "int main() {",
      "    std::cout << search({-1, 0, 3, 5, 9, 12}, 9) << std::endl;",
      "    return 0;",
      "}",
      "// O(log n) - the range halves every iteration",
    ],
    expectedOutput: "4",
  },

  "promise-pool": {
    starter: "#include <iostream>\n#include <vector>\n#include <functional>\n#include <thread>\n\nstd::vector<int> pool(const std::vector<std::function<int()>>& tasks, int limit) {\n    // your code here\n    return {};\n}\n\nint main() {\n    std::vector<std::function<int()>> tasks{[] { return 1; }, [] { return 2; }, [] { return 3; }};\n    for (int v : pool(tasks, 2)) std::cout << v << \" \";\n    std::cout << std::endl;  // 1 2 3\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "#include <functional>",
      "#include <thread>",
      "",
      "std::vector<int> pool(const std::vector<std::function<int()>>& tasks, int limit) {",
      "    std::vector<int> results(tasks.size());   // indexed by position, not finish order",
      "    size_t i = 0;",
      "    while (i < tasks.size()) {",
      "        // launch at most `limit` threads, then wait for the whole batch",
      "        std::vector<std::thread> batch;",
      "        for (int k = 0; k < limit && i < tasks.size(); ++k, ++i) {",
      "            size_t idx = i;",
      "            batch.emplace_back([&results, &tasks, idx] {",
      "                results[idx] = tasks[idx]();  // each writes its own slot - no race",
      "            });",
      "        }",
      "        for (auto& t : batch) t.join();       // drain before starting the next batch",
      "    }",
      "    return results;",
      "}",
      "",
      "int main() {",
      "    std::vector<std::function<int()>> tasks{[] { return 1; }, [] { return 2; }, [] { return 3; }};",
      "    for (int v : pool(tasks, 2)) std::cout << v << \" \";",
      "    std::cout << std::endl;",
      "    return 0;",
      "}",
      "// at most `limit` threads run at once, results keep their input order",
    ],
    expectedOutput: "1 2 3",
  },

  "group-anagrams": {
    starter: "#include <iostream>\n#include <vector>\n#include <string>\n#include <map>\n#include <algorithm>\n\nstd::vector<std::vector<std::string>> groupAnagrams(const std::vector<std::string>& strs) {\n    // your code here\n    return {};\n}\n\nint main() {\n    for (const auto& g : groupAnagrams({\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"})) {\n        for (const auto& w : g) std::cout << w << \" \";\n        std::cout << \"| \";\n    }\n    std::cout << std::endl;\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "#include <string>",
      "#include <map>",
      "#include <algorithm>",
      "",
      "std::vector<std::vector<std::string>> groupAnagrams(const std::vector<std::string>& strs) {",
      "    std::map<std::string, std::vector<std::string>> groups;",
      "    for (const auto& w : strs) {",
      "        std::string key = w;",
      "        std::sort(key.begin(), key.end());   // anagrams share sorted letters,",
      "        groups[key].push_back(w);            // so that is a stable group key",
      "    }",
      "    std::vector<std::vector<std::string>> out;",
      "    for (auto& kv : groups) out.push_back(kv.second);",
      "    return out;",
      "}",
      "",
      "int main() {",
      "    for (const auto& g : groupAnagrams({\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"})) {",
      "        for (const auto& w : g) std::cout << w << \" \";",
      "        std::cout << \"| \";",
      "    }",
      "    std::cout << std::endl;",
      "    return 0;",
      "}",
      "// O(n * k log k) for n words of length k",
    ],
    expectedOutput: "bat | eat tea ate | tan nat |",
  },

  "flatten": {
    starter: "#include <iostream>\n#include <vector>\n\n// a nested value is either a number or a list of nested values\nstruct Node {\n    bool isList;\n    int value;\n    std::vector<Node> children;\n};\n\nstd::vector<int> flatten(const Node& n) {\n    // your code here\n    return {};\n}\n\nint main() {\n    Node nested{true, 0, {{false, 1, {}}, {true, 0, {{false, 2, {}}}}}};\n    for (int v : flatten(nested)) std::cout << v << \" \";\n    std::cout << std::endl;  // 1 2\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "",
      "// a nested value is either a number or a list of nested values",
      "struct Node {",
      "    bool isList;",
      "    int value;",
      "    std::vector<Node> children;",
      "};",
      "",
      "std::vector<int> flatten(const Node& n) {",
      "    if (!n.isList) return {n.value};        // a leaf contributes itself",
      "    std::vector<int> out;",
      "    for (const auto& child : n.children) {",
      "        // recurse, then splice the child's numbers onto our result",
      "        std::vector<int> inner = flatten(child);",
      "        out.insert(out.end(), inner.begin(), inner.end());",
      "    }",
      "    return out;",
      "}",
      "",
      "int main() {",
      "    // [1, [2, [3, [4]]]]",
      "    Node four{true, 0, {{false, 4, {}}}};",
      "    Node three{true, 0, {{false, 3, {}}, four}};",
      "    Node two{true, 0, {{false, 2, {}}, three}};",
      "    Node root{true, 0, {{false, 1, {}}, two}};",
      "    for (int v : flatten(root)) std::cout << v << \" \";",
      "    std::cout << std::endl;",
      "    return 0;",
      "}",
      "// visits every node once - O(total elements)",
    ],
    expectedOutput: "1 2 3 4",
  },

  "longest-unique-substring": {
    starter: "#include <iostream>\n#include <string>\n#include <unordered_map>\n#include <algorithm>\n\nint lengthOfLongestSubstring(const std::string& s) {\n    // your code here\n    return 0;\n}\n\nint main() {\n    std::cout << lengthOfLongestSubstring(\"abcabcbb\") << std::endl;  // 3\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <string>",
      "#include <unordered_map>",
      "#include <algorithm>",
      "",
      "int lengthOfLongestSubstring(const std::string& s) {",
      "    std::unordered_map<char, int> seen;       // char -> last index it appeared at",
      "    int best = 0, start = 0;                  // start = the window's left edge",
      "    for (int i = 0; i < (int)s.size(); i++) {",
      "        auto it = seen.find(s[i]);",
      "        // only move the window forward, never back past `start`",
      "        if (it != seen.end() && it->second >= start) start = it->second + 1;",
      "        seen[s[i]] = i;",
      "        best = std::max(best, i - start + 1); // window size",
      "    }",
      "    return best;",
      "}",
      "",
      "int main() {",
      "    std::cout << lengthOfLongestSubstring(\"abcabcbb\") << std::endl;",
      "    return 0;",
      "}",
      "// sliding window - O(n), each character handled once",
    ],
    expectedOutput: "3",
  },

  "merge-intervals": {
    starter: "#include <iostream>\n#include <vector>\n#include <algorithm>\n\nstd::vector<std::vector<int>> merge(std::vector<std::vector<int>> intervals) {\n    // your code here\n    return {};\n}\n\nint main() {\n    for (const auto& iv : merge({{1, 3}, {2, 6}, {8, 10}, {15, 18}}))\n        std::cout << \"[\" << iv[0] << \",\" << iv[1] << \"] \";\n    std::cout << std::endl;\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "#include <algorithm>",
      "",
      "std::vector<std::vector<int>> merge(std::vector<std::vector<int>> intervals) {",
      "    // sort by start so any overlaps end up next to each other",
      "    std::sort(intervals.begin(), intervals.end(),",
      "              [](const std::vector<int>& a, const std::vector<int>& b) {",
      "                  return a[0] < b[0];",
      "              });",
      "    std::vector<std::vector<int>> out;",
      "    for (const auto& iv : intervals) {",
      "        // starts before the previous one ended -> overlap, so stretch it",
      "        if (!out.empty() && iv[0] <= out.back()[1])",
      "            out.back()[1] = std::max(out.back()[1], iv[1]);",
      "        else",
      "            out.push_back(iv);                // no overlap: begin a new range",
      "    }",
      "    return out;",
      "}",
      "",
      "int main() {",
      "    for (const auto& iv : merge({{1, 3}, {2, 6}, {8, 10}, {15, 18}}))",
      "        std::cout << \"[\" << iv[0] << \",\" << iv[1] << \"] \";",
      "    std::cout << std::endl;",
      "    return 0;",
      "}",
      "// O(n log n), dominated by the sort",
    ],
    expectedOutput: "[1,6] [8,10] [15,18]",
  },

  "reverse-list": {
    starter: "#include <iostream>\n\nstruct Node {\n    int val;\n    Node* next;\n    Node(int v, Node* n = nullptr) : val(v), next(n) {}\n};\n\nNode* reverseList(Node* head) {\n    // your code here\n    return nullptr;\n}\n\nint main() {\n    Node* head = new Node(1, new Node(2, new Node(3)));\n    for (Node* r = reverseList(head); r; r = r->next) std::cout << r->val << \" \";\n    std::cout << std::endl;  // 3 2 1\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "",
      "struct Node {",
      "    int val;",
      "    Node* next;",
      "    Node(int v, Node* n = nullptr) : val(v), next(n) {}",
      "};",
      "",
      "Node* reverseList(Node* head) {",
      "    Node* prev = nullptr;",
      "    Node* cur = head;",
      "    while (cur) {",
      "        Node* next = cur->next;   // save the rest before overwriting the link",
      "        cur->next = prev;         // point this node backwards",
      "        prev = cur;               // prev follows cur forward",
      "        cur = next;               // carry on down the original list",
      "    }",
      "    return prev;                  // cur is null, so prev is the new head",
      "}",
      "",
      "int main() {",
      "    Node* head = new Node(1, new Node(2, new Node(3)));",
      "    for (Node* r = reverseList(head); r; r = r->next) std::cout << r->val << \" \";",
      "    std::cout << std::endl;",
      "    return 0;",
      "}",
      "// O(n) time, O(1) space - three pointers, no new nodes",
    ],
    expectedOutput: "3 2 1",
  },

  "search-rotated": {
    starter: "#include <iostream>\n#include <vector>\n\nint searchRotated(const std::vector<int>& nums, int target) {\n    // your code here\n    return -1;\n}\n\nint main() {\n    std::cout << searchRotated({4, 5, 6, 7, 0, 1, 2}, 0) << std::endl;  // 4\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "",
      "int searchRotated(const std::vector<int>& nums, int target) {",
      "    int lo = 0, hi = (int)nums.size() - 1;",
      "    while (lo <= hi) {",
      "        int mid = lo + (hi - lo) / 2;",
      "        if (nums[mid] == target) return mid;",
      "        // whatever the rotation, one side of mid is always sorted",
      "        if (nums[lo] <= nums[mid]) {               // left half is sorted",
      "            // inside that range? search it, otherwise take the other half",
      "            if (nums[lo] <= target && target < nums[mid]) hi = mid - 1;",
      "            else lo = mid + 1;",
      "        } else {                                   // right half is sorted",
      "            if (nums[mid] < target && target <= nums[hi]) lo = mid + 1;",
      "            else hi = mid - 1;",
      "        }",
      "    }",
      "    return -1;",
      "}",
      "",
      "int main() {",
      "    std::cout << searchRotated({4, 5, 6, 7, 0, 1, 2}, 0) << std::endl;",
      "    return 0;",
      "}",
      "// still O(log n) - one comparison discards half the range",
    ],
    expectedOutput: "4",
  },

  "num-islands-dfs": {
    starter: "#include <iostream>\n#include <vector>\n\nint numIslands(std::vector<std::vector<char>>& grid) {\n    // your code here\n    return 0;\n}\n\nint main() {\n    std::vector<std::vector<char>> grid{\n        {'1', '1', '0'},\n        {'1', '1', '0'},\n        {'0', '0', '0'},\n    };\n    std::cout << numIslands(grid) << std::endl;  // 1\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "",
      "// flood fill: sink every cell of an island so it is counted only once",
      "static void sink(std::vector<std::vector<char>>& grid, int r, int c) {",
      "    if (r < 0 || c < 0 || r >= (int)grid.size()) return;   // off vertically",
      "    if (c >= (int)grid[0].size()) return;                  // off the right edge",
      "    if (grid[r][c] != '1') return;                         // water or already sunk",
      "    grid[r][c] = '0';                                      // mark visited",
      "    sink(grid, r + 1, c); sink(grid, r - 1, c);            // spread vertically",
      "    sink(grid, r, c + 1); sink(grid, r, c - 1);            // and horizontally",
      "}",
      "",
      "int numIslands(std::vector<std::vector<char>>& grid) {",
      "    int count = 0;",
      "    for (int r = 0; r < (int)grid.size(); r++)",
      "        for (int c = 0; c < (int)grid[0].size(); c++)",
      "            // each land cell still standing begins exactly one new island",
      "            if (grid[r][c] == '1') { count++; sink(grid, r, c); }",
      "    return count;",
      "}",
      "",
      "int main() {",
      "    std::vector<std::vector<char>> grid{",
      "        {'1', '1', '0'},",
      "        {'1', '1', '0'},",
      "        {'0', '0', '0'},",
      "    };",
      "    std::cout << numIslands(grid) << std::endl;",
      "    return 0;",
      "}",
      "// O(rows * cols) - each cell is touched a constant number of times",
    ],
    expectedOutput: "1",
  },

  "top-k-frequent-bucket": {
    starter: "#include <iostream>\n#include <vector>\n#include <unordered_map>\n#include <algorithm>\n\nstd::vector<int> topKFrequent(const std::vector<int>& nums, int k) {\n    // your code here\n    return {};\n}\n\nint main() {\n    std::vector<int> r = topKFrequent({1, 1, 1, 2, 2, 3}, 2);\n    std::sort(r.begin(), r.end());\n    for (int v : r) std::cout << v << \" \";\n    std::cout << std::endl;  // 1 2\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <vector>",
      "#include <unordered_map>",
      "#include <algorithm>",
      "",
      "std::vector<int> topKFrequent(const std::vector<int>& nums, int k) {",
      "    std::unordered_map<int, int> freq;",
      "    for (int n : nums) freq[n]++;              // count how often each value appears",
      "    // buckets[i] holds every value seen exactly i times; i never exceeds n",
      "    std::vector<std::vector<int>> buckets(nums.size() + 1);",
      "    for (const auto& kv : freq) buckets[kv.second].push_back(kv.first);",
      "    std::vector<int> out;",
      "    // walk down from the highest possible count until we have k values",
      "    for (int c = (int)buckets.size() - 1; c >= 0 && (int)out.size() < k; c--)",
      "        for (int v : buckets[c]) out.push_back(v);",
      "    out.resize(std::min((size_t)k, out.size()));   // trim any overshoot",
      "    return out;",
      "}",
      "",
      "int main() {",
      "    std::vector<int> r = topKFrequent({1, 1, 1, 2, 2, 3}, 2);",
      "    std::sort(r.begin(), r.end());",
      "    for (int v : r) std::cout << v << \" \";",
      "    std::cout << std::endl;",
      "    return 0;",
      "}",
      "// bucket sort - O(n), beats a heap's O(n log k) here",
    ],
    expectedOutput: "1 2",
  },

  "climb-stairs-dp": {
    starter: "#include <iostream>\n\nint climbStairs(int n) {\n    // your code here\n    return 0;\n}\n\nint main() {\n    std::cout << climbStairs(5) << std::endl;  // 8\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "",
      "int climbStairs(int n) {",
      "    // step n is reached from n-1 (one step) or n-2 (two), so counts add",
      "    int a = 1, b = 1;             // ways to stand at step 0 and step 1",
      "    for (int i = 2; i <= n; i++) {",
      "        int next = a + b;         // slide the two-value window forward",
      "        a = b;",
      "        b = next;",
      "    }",
      "    return b;",
      "}",
      "",
      "int main() {",
      "    std::cout << climbStairs(5) << std::endl;",
      "    return 0;",
      "}",
      "// Fibonacci in disguise - O(n) time, O(1) space",
    ],
    expectedOutput: "8",
  },

  "url-shortener": {
    starter: "#include <iostream>\n#include <string>\n#include <unordered_map>\n\nclass UrlShortener {\npublic:\n    std::string shorten(const std::string& url) {\n        // your code here\n        return \"\";\n    }\n\n    std::string expand(const std::string& shortUrl) {\n        // your code here\n        return \"\";\n    }\n};\n\nint main() {\n    UrlShortener s;\n    std::string shortUrl = s.shorten(\"https://example.com\");\n    std::cout << shortUrl << \" \" << s.expand(shortUrl) << std::endl;\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <string>",
      "#include <unordered_map>",
      "",
      "static const std::string CHARS =",
      "    \"abcdefghijklmnopqrstuvwxyz\"",
      "    \"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\";",
      "",
      "// turn a counter into a short slug - 62 symbols per character",
      "static std::string base62(long long n) {",
      "    std::string s;",
      "    do {",
      "        s = CHARS[n % 62] + s;    // lowest base-62 digit first, prepended",
      "        n /= 62;                  // shift right one digit",
      "    } while (n > 0);",
      "    return s;",
      "}",
      "",
      "class UrlShortener {",
      "public:",
      "    std::string shorten(const std::string& url) {",
      "        std::string slug = base62(next_++);   // consume one counter value",
      "        urls_[slug] = url;",
      "        return \"sho.rt/\" + slug;",
      "    }",
      "",
      "    std::string expand(const std::string& shortUrl) {",
      "        // accept a full short link or a bare slug",
      "        size_t slash = shortUrl.rfind('/');",
      "        std::string slug = slash == std::string::npos",
      "            ? shortUrl : shortUrl.substr(slash + 1);",
      "        auto it = urls_.find(slug);",
      "        return it == urls_.end() ? \"\" : it->second;",
      "    }",
      "",
      "private:",
      "    std::unordered_map<std::string, std::string> urls_;  // slug -> url",
      "    long long next_ = 1;   // a counter, not a hash - so slugs never collide",
      "};",
      "",
      "int main() {",
      "    UrlShortener s;",
      "    std::string shortUrl = s.shorten(\"https://example.com\");",
      "    std::cout << shortUrl << \" \" << s.expand(shortUrl) << std::endl;",
      "    return 0;",
      "}",
      "// 7 chars of base62 is about 3.5 trillion ids",
    ],
    expectedOutput: "sho.rt/b https://example.com",
  },

  "sliding-window-limiter": {
    starter: "#include <iostream>\n#include <string>\n#include <vector>\n#include <unordered_map>\n#include <chrono>\n\nclass SlidingWindowLimiter {\npublic:\n    SlidingWindowLimiter(int limit, long windowMs) {\n        // your code here\n    }\n\n    bool allow(const std::string& key) {\n        // your code here\n        return false;\n    }\n};\n\nint main() {\n    SlidingWindowLimiter l(2, 1000);\n    std::cout << l.allow(\"a\") << \" \" << l.allow(\"a\") << \" \" << l.allow(\"a\") << std::endl;\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <string>",
      "#include <vector>",
      "#include <unordered_map>",
      "#include <chrono>",
      "#include <algorithm>",
      "",
      "static long nowMs() {",
      "    using namespace std::chrono;",
      "    return duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count();",
      "}",
      "",
      "class SlidingWindowLimiter {",
      "public:",
      "    SlidingWindowLimiter(int limit, long windowMs) : limit_(limit), win_(windowMs) {}",
      "",
      "    bool allow(const std::string& key) {",
      "        long now = nowMs();",
      "        std::vector<long>& log = hits_[key];",
      "        // drop timestamps that aged out - this is what makes it \"sliding\"",
      "        log.erase(std::remove_if(log.begin(), log.end(),",
      "                                 [&](long t) { return now - t >= win_; }),",
      "                  log.end());",
      "        if ((int)log.size() >= limit_) return false;  // budget already spent",
      "        log.push_back(now);                           // record this call",
      "        return true;",
      "    }",
      "",
      "private:",
      "    int limit_;",
      "    long win_;",
      "    std::unordered_map<std::string, std::vector<long>> hits_;  // key -> timestamps",
      "};",
      "",
      "int main() {",
      "    SlidingWindowLimiter l(2, 1000);",
      "    std::cout << l.allow(\"a\") << \" \" << l.allow(\"a\") << \" \" << l.allow(\"a\") << std::endl;",
      "    return 0;",
      "}",
      "// exact, but O(hits) memory - a token bucket scales better",
    ],
    expectedOutput: "1 1 0",
  },

  "throttle": {
    starter: "#include <iostream>\n#include <functional>\n#include <thread>\n#include <chrono>\n#include <atomic>\n\nclass Throttler {\npublic:\n    Throttler(int waitMs) {\n        // your code here\n    }\n\n    void call(std::function<void()> fn) {\n        // your code here\n    }\n};\n\nint main() {\n    std::atomic<int> n{0};\n    Throttler t(80);\n    t.call([&] { n++; });\n    t.call([&] { n++; });\n    t.call([&] { n++; });\n    std::this_thread::sleep_for(std::chrono::milliseconds(250));\n    std::cout << n.load() << std::endl;  // 2\n    return 0;\n}",
    solution: [
      "#include <iostream>",
      "#include <functional>",
      "#include <thread>",
      "#include <chrono>",
      "#include <atomic>",
      "#include <mutex>",
      "",
      "static long nowMs() {",
      "    using namespace std::chrono;",
      "    return duration_cast<milliseconds>(steady_clock::now().time_since_epoch()).count();",
      "}",
      "",
      "class Throttler {",
      "public:",
      "    explicit Throttler(int waitMs) : waitMs_(waitMs) {}",
      "",
      "    void call(std::function<void()> fn) {",
      "        std::unique_lock<std::mutex> lock(m_);",
      "        long now = nowMs();",
      "        long left = waitMs_ - (now - last_);   // ms until the window reopens",
      "        if (left <= 0) {                       // window open - fire right away",
      "            last_ = now;",
      "            lock.unlock();",
      "            fn();",
      "            return;",
      "        }",
      "        if (pending_) return;                  // a trailing call is already queued",
      "        pending_ = true;",
      "        std::thread([this, fn, left] {",
      "            std::this_thread::sleep_for(std::chrono::milliseconds(left));",
      "            {",
      "                std::lock_guard<std::mutex> lock(m_);",
      "                last_ = nowMs();",
      "                pending_ = false;              // let the next burst queue again",
      "            }",
      "            fn();",
      "        }).detach();",
      "    }",
      "",
      "private:",
      "    int waitMs_;",
      "    long last_ = 0;",
      "    bool pending_ = false;",
      "    std::mutex m_;",
      "};",
      "",
      "int main() {",
      "    std::atomic<int> n{0};",
      "    Throttler t(80);",
      "    t.call([&] { n++; });",
      "    t.call([&] { n++; });",
      "    t.call([&] { n++; });",
      "    std::this_thread::sleep_for(std::chrono::milliseconds(250));",
      "    std::cout << n.load() << std::endl;",
      "    return 0;",
      "}",
      "// leading + trailing edge: a burst produces exactly two calls",
    ],
    expectedOutput: "2",
  },
};
