import type { LangTable } from "./index";

// Go starters and reference solutions. Each entry is a complete `package main`
// that prints a result, matching how Judge0 builds a single file.
export const GO: LangTable = {
  "two-sum": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc twoSum(nums []int, target int) []int {\n\t// your code here\n\treturn nil\n}\n\nfunc main() {\n\tfmt.Println(twoSum([]int{2, 7, 11, 15}, 9)) // [0 1]\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func twoSum(nums []int, target int) []int {",
      "\tseen := make(map[int]int)        // value -> its index",
      "\tfor i, n := range nums {",
      "\t\tneed := target - n           // the partner we want",
      "\t\tif j, ok := seen[need]; ok { // met it already?",
      "\t\t\treturn []int{j, i}",
      "\t\t}",
      "\t\tseen[n] = i                  // remember for later",
      "\t}",
      "\treturn nil",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(twoSum([]int{2, 7, 11, 15}, 9))",
      "}",
      "// O(n) time, O(n) space - one pass, O(1) map lookups",
    ],
    expectedOutput: "[0 1]",
  },

  "max-subarray": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc maxSubArray(nums []int) int {\n\t// your code here\n\treturn 0\n}\n\nfunc main() {\n\tfmt.Println(maxSubArray([]int{-2, 1, -3, 4, -1, 2, 1, -5, 4})) // 6\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func maxSubArray(nums []int) int {",
      "\tbest, cur := nums[0], nums[0]    // both start on element 0",
      "\tfor _, n := range nums[1:] {",
      "\t\t// extending only helps if the run so far is not dragging us down",
      "\t\tif cur+n > n {",
      "\t\t\tcur = cur + n",
      "\t\t} else {",
      "\t\t\tcur = n",
      "\t\t}",
      "\t\tif cur > best {",
      "\t\t\tbest = cur               // remember the best run seen",
      "\t\t}",
      "\t}",
      "\treturn best",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(maxSubArray([]int{-2, 1, -3, 4, -1, 2, 1, -5, 4}))",
      "}",
      "// Kadane's algorithm - O(n) time, O(1) space",
    ],
    expectedOutput: "6",
  },

  "valid-parens": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc isValid(s string) bool {\n\t// your code here\n\treturn false\n}\n\nfunc main() {\n\tfmt.Println(isValid(\"()[]{}\")) // true\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func isValid(s string) bool {",
      "\tpairs := map[rune]rune{')': '(', ']': '[', '}': '{'} // closer -> its opener",
      "\tstack := []rune{}",
      "\tfor _, ch := range s {",
      "\t\topen, isCloser := pairs[ch]",
      "\t\tif !isCloser {                     // an opener: remember it",
      "\t\t\tstack = append(stack, ch)",
      "\t\t\tcontinue",
      "\t\t}",
      "\t\t// a closer must match the most recent unclosed opener",
      "\t\tif len(stack) == 0 || stack[len(stack)-1] != open {",
      "\t\t\treturn false",
      "\t\t}",
      "\t\tstack = stack[:len(stack)-1]",
      "\t}",
      "\treturn len(stack) == 0                 // anything left open is invalid",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(isValid(\"()[]{}\"))",
      "}",
      "// O(n) time, O(n) space",
    ],
    expectedOutput: "true",
  },

  "lru": {
    starter: "package main\n\nimport \"fmt\"\n\ntype LRUCache struct {\n\t// your code here\n}\n\nfunc NewLRUCache(cap int) *LRUCache {\n\t// your code here\n\treturn &LRUCache{}\n}\n\nfunc (c *LRUCache) Get(k int) int {\n\t// your code here\n\treturn -1\n}\n\nfunc (c *LRUCache) Put(k, v int) {\n\t// your code here\n}\n\nfunc main() {\n\tc := NewLRUCache(2)\n\tc.Put(1, 1)\n\tc.Put(2, 2)\n\tfmt.Println(c.Get(1)) // 1\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"container/list\"",
      "\t\"fmt\"",
      ")",
      "",
      "type entry struct{ k, v int }",
      "",
      "type LRUCache struct {",
      "\tcap   int",
      "\torder *list.List             // front = most recent, back = least",
      "\tpos   map[int]*list.Element  // key -> its node",
      "}",
      "",
      "func NewLRUCache(cap int) *LRUCache {",
      "\treturn &LRUCache{cap: cap, order: list.New(), pos: make(map[int]*list.Element)}",
      "}",
      "",
      "func (c *LRUCache) Get(k int) int {",
      "\tel, ok := c.pos[k]",
      "\tif !ok {",
      "\t\treturn -1                       // miss",
      "\t}",
      "\tc.order.MoveToFront(el)             // mark as most-recently-used",
      "\treturn el.Value.(*entry).v",
      "}",
      "",
      "func (c *LRUCache) Put(k, v int) {",
      "\tif el, ok := c.pos[k]; ok {         // already present: refresh",
      "\t\tel.Value.(*entry).v = v",
      "\t\tc.order.MoveToFront(el)",
      "\t\treturn",
      "\t}",
      "\tc.pos[k] = c.order.PushFront(&entry{k, v})",
      "\tif c.order.Len() > c.cap {",
      "\t\tlast := c.order.Back()          // back = least recently used",
      "\t\tdelete(c.pos, last.Value.(*entry).k)",
      "\t\tc.order.Remove(last)",
      "\t}",
      "}",
      "",
      "func main() {",
      "\tc := NewLRUCache(2)",
      "\tc.Put(1, 1)",
      "\tc.Put(2, 2)",
      "\tfmt.Println(c.Get(1))",
      "\tc.Put(3, 3)",
      "\tfmt.Println(c.Get(2))",
      "}",
      "// O(1) get and put - a list for order, a map for lookup",
    ],
    expectedOutput: "1\n-1",
  },

  "rate-limiter": {
    starter: "package main\n\nimport \"fmt\"\n\ntype RateLimiter struct {\n\t// your code here\n}\n\nfunc NewRateLimiter(rate float64, per float64) *RateLimiter {\n\t// your code here\n\treturn &RateLimiter{}\n}\n\nfunc (r *RateLimiter) Allow() bool {\n\t// your code here\n\treturn false\n}\n\nfunc main() {\n\tr := NewRateLimiter(2, 1000)\n\tfmt.Println(r.Allow(), r.Allow(), r.Allow())\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"time\"",
      ")",
      "",
      "type RateLimiter struct {",
      "\trate, per, tokens float64",
      "\tlast              time.Time",
      "}",
      "",
      "func NewRateLimiter(rate float64, per float64) *RateLimiter {",
      "\t// bucket starts full, so a burst up to rate works immediately",
      "\treturn &RateLimiter{rate: rate, per: per, tokens: rate, last: time.Now()}",
      "}",
      "",
      "func (r *RateLimiter) Allow() bool {",
      "\tnow := time.Now()",
      "\telapsed := float64(now.Sub(r.last).Milliseconds())",
      "\t// refill continuously: elapsed/per is the fraction of a bucket earned",
      "\tr.tokens += (elapsed / r.per) * r.rate",
      "\tif r.tokens > r.rate {",
      "\t\tr.tokens = r.rate            // never over-fill",
      "\t}",
      "\tr.last = now",
      "\tif r.tokens < 1 {",
      "\t\treturn false                 // not even one whole token",
      "\t}",
      "\tr.tokens--                       // spend it",
      "\treturn true",
      "}",
      "",
      "func main() {",
      "\tr := NewRateLimiter(2, 1000)",
      "\tfmt.Println(r.Allow(), r.Allow(), r.Allow())",
      "}",
      "// O(1) time and memory - no request history is kept",
    ],
    expectedOutput: "true true false",
  },

  "debounce": {
    starter: "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\nfunc debounce(wait time.Duration) func(func()) {\n\t// your code here\n\treturn func(fn func()) {}\n}\n\nfunc main() {\n\tn := 0\n\tcall := debounce(50 * time.Millisecond)\n\tcall(func() { n++ })\n\tcall(func() { n++ })\n\ttime.Sleep(200 * time.Millisecond)\n\tfmt.Println(n) // 1\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"sync\"",
      "\t\"time\"",
      ")",
      "",
      "func debounce(wait time.Duration) func(func()) {",
      "\tvar mu sync.Mutex",
      "\tvar timer *time.Timer",
      "\treturn func(fn func()) {",
      "\t\tmu.Lock()",
      "\t\tdefer mu.Unlock()",
      "\t\tif timer != nil {",
      "\t\t\ttimer.Stop()          // a new call cancels the pending one",
      "\t\t}",
      "\t\t// only the final call of a burst survives long enough to fire",
      "\t\ttimer = time.AfterFunc(wait, fn)",
      "\t}",
      "}",
      "",
      "func main() {",
      "\tn := 0",
      "\tvar mu sync.Mutex",
      "\tcall := debounce(50 * time.Millisecond)",
      "\tbump := func() { mu.Lock(); n++; mu.Unlock() }",
      "\tcall(bump)",
      "\tcall(bump)",
      "\tcall(bump)",
      "\ttime.Sleep(200 * time.Millisecond)",
      "\tmu.Lock()",
      "\tfmt.Println(n)",
      "\tmu.Unlock()",
      "}",
      "// every call restarts the clock, so fn runs once the calls stop",
    ],
    expectedOutput: "1",
  },

  "binary-search": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc search(nums []int, target int) int {\n\t// your code here\n\treturn -1\n}\n\nfunc main() {\n\tfmt.Println(search([]int{-1, 0, 3, 5, 9, 12}, 9)) // 4\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func search(nums []int, target int) int {",
      "\tlo, hi := 0, len(nums)-1         // inclusive bounds",
      "\tfor lo <= hi {",
      "\t\tmid := lo + (hi-lo)/2        // written this way to avoid overflow",
      "\t\tswitch {",
      "\t\tcase nums[mid] == target:",
      "\t\t\treturn mid",
      "\t\tcase nums[mid] < target:",
      "\t\t\tlo = mid + 1             // answer lies to the right",
      "\t\tdefault:",
      "\t\t\thi = mid - 1             // answer lies to the left",
      "\t\t}",
      "\t}",
      "\treturn -1                        // bounds crossed - not present",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(search([]int{-1, 0, 3, 5, 9, 12}, 9))",
      "}",
      "// O(log n) - the range halves every iteration",
    ],
    expectedOutput: "4",
  },

  "promise-pool": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc pool(tasks []func() int, limit int) []int {\n\t// your code here\n\treturn nil\n}\n\nfunc main() {\n\ttasks := []func() int{func() int { return 1 }, func() int { return 2 }, func() int { return 3 }}\n\tfmt.Println(pool(tasks, 2)) // [1 2 3]\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"sync\"",
      ")",
      "",
      "func pool(tasks []func() int, limit int) []int {",
      "\tresults := make([]int, len(tasks))   // indexed by position, not finish order",
      "\tsem := make(chan struct{}, limit)    // a buffered channel IS the limit",
      "\tvar wg sync.WaitGroup",
      "\tfor i, task := range tasks {",
      "\t\twg.Add(1)",
      "\t\tgo func(i int, task func() int) {",
      "\t\t\tdefer wg.Done()",
      "\t\t\tsem <- struct{}{}            // blocks once `limit` are in flight",
      "\t\t\tdefer func() { <-sem }()",
      "\t\t\tresults[i] = task()          // each writes its own slot - no race",
      "\t\t}(i, task)",
      "\t}",
      "\twg.Wait()",
      "\treturn results",
      "}",
      "",
      "func main() {",
      "\ttasks := []func() int{func() int { return 1 }, func() int { return 2 }, func() int { return 3 }}",
      "\tfmt.Println(pool(tasks, 2))",
      "}",
      "// at most `limit` goroutines run at once, results keep input order",
    ],
    expectedOutput: "[1 2 3]",
  },

  "group-anagrams": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc groupAnagrams(strs []string) [][]string {\n\t// your code here\n\treturn nil\n}\n\nfunc main() {\n\tfmt.Println(groupAnagrams([]string{\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"}))\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"sort\"",
      ")",
      "",
      "func groupAnagrams(strs []string) [][]string {",
      "\tgroups := make(map[string][]string)",
      "\tvar keys []string",
      "\tfor _, w := range strs {",
      "\t\tb := []byte(w)",
      "\t\tsort.Slice(b, func(i, j int) bool { return b[i] < b[j] })",
      "\t\tkey := string(b)               // anagrams share sorted letters",
      "\t\tif _, seen := groups[key]; !seen {",
      "\t\t\tkeys = append(keys, key)   // keep first-seen order stable",
      "\t\t}",
      "\t\tgroups[key] = append(groups[key], w)",
      "\t}",
      "\tout := make([][]string, 0, len(keys))",
      "\tfor _, k := range keys {",
      "\t\tout = append(out, groups[k])",
      "\t}",
      "\treturn out",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(groupAnagrams([]string{\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"}))",
      "}",
      "// O(n * k log k) for n words of length k",
    ],
    expectedOutput: "[[eat tea ate] [tan nat] [bat]]",
  },

  "flatten": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc flatten(arr []interface{}) []int {\n\t// your code here\n\treturn nil\n}\n\nfunc main() {\n\tnested := []interface{}{1, []interface{}{2, []interface{}{3, []interface{}{4}}}}\n\tfmt.Println(flatten(nested)) // [1 2 3 4]\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func flatten(arr []interface{}) []int {",
      "\tout := []int{}",
      "\tfor _, x := range arr {",
      "\t\t// recurse into nested slices, keep every other value as it is",
      "\t\tif inner, ok := x.([]interface{}); ok {",
      "\t\t\tout = append(out, flatten(inner)...)",
      "\t\t} else if n, ok := x.(int); ok {",
      "\t\t\tout = append(out, n)",
      "\t\t}",
      "\t}",
      "\treturn out",
      "}",
      "",
      "func main() {",
      "\tnested := []interface{}{1, []interface{}{2, []interface{}{3, []interface{}{4}}}}",
      "\tfmt.Println(flatten(nested))",
      "}",
      "// visits every element once - O(total elements)",
    ],
    expectedOutput: "[1 2 3 4]",
  },

  "longest-unique-substring": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc lengthOfLongestSubstring(s string) int {\n\t// your code here\n\treturn 0\n}\n\nfunc main() {\n\tfmt.Println(lengthOfLongestSubstring(\"abcabcbb\")) // 3\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func lengthOfLongestSubstring(s string) int {",
      "\tseen := make(map[byte]int)       // char -> last index it appeared at",
      "\tbest, start := 0, 0              // start = the window's left edge",
      "\tfor i := 0; i < len(s); i++ {",
      "\t\t// only move the window forward, never back past `start`",
      "\t\tif prev, ok := seen[s[i]]; ok && prev >= start {",
      "\t\t\tstart = prev + 1",
      "\t\t}",
      "\t\tseen[s[i]] = i",
      "\t\tif i-start+1 > best {",
      "\t\t\tbest = i - start + 1     // window size",
      "\t\t}",
      "\t}",
      "\treturn best",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(lengthOfLongestSubstring(\"abcabcbb\"))",
      "}",
      "// sliding window - O(n), each character handled once",
    ],
    expectedOutput: "3",
  },

  "merge-intervals": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc merge(intervals [][]int) [][]int {\n\t// your code here\n\treturn nil\n}\n\nfunc main() {\n\tfmt.Println(merge([][]int{{1, 3}, {2, 6}, {8, 10}, {15, 18}}))\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"sort\"",
      ")",
      "",
      "func merge(intervals [][]int) [][]int {",
      "\t// sort by start so any overlaps end up next to each other",
      "\tsort.Slice(intervals, func(i, j int) bool { return intervals[i][0] < intervals[j][0] })",
      "\tout := [][]int{}",
      "\tfor _, iv := range intervals {",
      "\t\tlast := len(out) - 1",
      "\t\t// starts before the previous one ended -> overlap, so stretch it",
      "\t\tif last >= 0 && iv[0] <= out[last][1] {",
      "\t\t\tif iv[1] > out[last][1] {",
      "\t\t\t\tout[last][1] = iv[1]",
      "\t\t\t}",
      "\t\t\tcontinue",
      "\t\t}",
      "\t\tout = append(out, []int{iv[0], iv[1]})  // no overlap: new range",
      "\t}",
      "\treturn out",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(merge([][]int{{1, 3}, {2, 6}, {8, 10}, {15, 18}}))",
      "}",
      "// O(n log n), dominated by the sort",
    ],
    expectedOutput: "[[1 6] [8 10] [15 18]]",
  },

  "reverse-list": {
    starter: "package main\n\nimport \"fmt\"\n\ntype Node struct {\n\tVal  int\n\tNext *Node\n}\n\nfunc reverseList(head *Node) *Node {\n\t// your code here\n\treturn nil\n}\n\nfunc main() {\n\thead := &Node{1, &Node{2, &Node{3, nil}}}\n\tfor r := reverseList(head); r != nil; r = r.Next {\n\t\tfmt.Print(r.Val, \" \")\n\t}\n\tfmt.Println() // 3 2 1\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "type Node struct {",
      "\tVal  int",
      "\tNext *Node",
      "}",
      "",
      "func reverseList(head *Node) *Node {",
      "\tvar prev *Node",
      "\tcur := head",
      "\tfor cur != nil {",
      "\t\tnext := cur.Next   // save the rest before overwriting the link",
      "\t\tcur.Next = prev    // point this node backwards",
      "\t\tprev = cur         // prev follows cur forward",
      "\t\tcur = next         // carry on down the original list",
      "\t}",
      "\treturn prev            // cur is nil, so prev is the new head",
      "}",
      "",
      "func main() {",
      "\thead := &Node{1, &Node{2, &Node{3, nil}}}",
      "\tfor r := reverseList(head); r != nil; r = r.Next {",
      "\t\tfmt.Print(r.Val, \" \")",
      "\t}",
      "\tfmt.Println()",
      "}",
      "// O(n) time, O(1) space - three pointers, no new nodes",
    ],
    expectedOutput: "3 2 1",
  },

  "search-rotated": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc searchRotated(nums []int, target int) int {\n\t// your code here\n\treturn -1\n}\n\nfunc main() {\n\tfmt.Println(searchRotated([]int{4, 5, 6, 7, 0, 1, 2}, 0)) // 4\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func searchRotated(nums []int, target int) int {",
      "\tlo, hi := 0, len(nums)-1",
      "\tfor lo <= hi {",
      "\t\tmid := lo + (hi-lo)/2",
      "\t\tif nums[mid] == target {",
      "\t\t\treturn mid",
      "\t\t}",
      "\t\t// whatever the rotation, one side of mid is always sorted",
      "\t\tif nums[lo] <= nums[mid] {           // left half is sorted",
      "\t\t\t// inside that range? search it, otherwise take the other half",
      "\t\t\tif nums[lo] <= target && target < nums[mid] {",
      "\t\t\t\thi = mid - 1",
      "\t\t\t} else {",
      "\t\t\t\tlo = mid + 1",
      "\t\t\t}",
      "\t\t} else {                             // right half is sorted",
      "\t\t\tif nums[mid] < target && target <= nums[hi] {",
      "\t\t\t\tlo = mid + 1",
      "\t\t\t} else {",
      "\t\t\t\thi = mid - 1",
      "\t\t\t}",
      "\t\t}",
      "\t}",
      "\treturn -1",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(searchRotated([]int{4, 5, 6, 7, 0, 1, 2}, 0))",
      "}",
      "// still O(log n) - one comparison discards half the range",
    ],
    expectedOutput: "4",
  },

  "num-islands-dfs": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc numIslands(grid [][]byte) int {\n\t// your code here\n\treturn 0\n}\n\nfunc main() {\n\tgrid := [][]byte{\n\t\t{'1', '1', '0'},\n\t\t{'1', '1', '0'},\n\t\t{'0', '0', '0'},\n\t}\n\tfmt.Println(numIslands(grid)) // 1\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "// flood fill: sink every cell of an island so it is counted only once",
      "func sink(grid [][]byte, r, c int) {",
      "\tif r < 0 || c < 0 || r >= len(grid) || c >= len(grid[0]) {",
      "\t\treturn                            // off the grid",
      "\t}",
      "\tif grid[r][c] != '1' {",
      "\t\treturn                            // water, or already sunk",
      "\t}",
      "\tgrid[r][c] = '0'                      // mark visited",
      "\tsink(grid, r+1, c)",
      "\tsink(grid, r-1, c)",
      "\tsink(grid, r, c+1)",
      "\tsink(grid, r, c-1)",
      "}",
      "",
      "func numIslands(grid [][]byte) int {",
      "\tcount := 0",
      "\tfor r := range grid {",
      "\t\tfor c := range grid[0] {",
      "\t\t\t// each land cell still standing begins exactly one new island",
      "\t\t\tif grid[r][c] == '1' {",
      "\t\t\t\tcount++",
      "\t\t\t\tsink(grid, r, c)",
      "\t\t\t}",
      "\t\t}",
      "\t}",
      "\treturn count",
      "}",
      "",
      "func main() {",
      "\tgrid := [][]byte{",
      "\t\t{'1', '1', '0'},",
      "\t\t{'1', '1', '0'},",
      "\t\t{'0', '0', '0'},",
      "\t}",
      "\tfmt.Println(numIslands(grid))",
      "}",
      "// O(rows * cols) - each cell is touched a constant number of times",
    ],
    expectedOutput: "1",
  },

  "top-k-frequent-bucket": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc topKFrequent(nums []int, k int) []int {\n\t// your code here\n\treturn nil\n}\n\nfunc main() {\n\tfmt.Println(topKFrequent([]int{1, 1, 1, 2, 2, 3}, 2))\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"sort\"",
      ")",
      "",
      "func topKFrequent(nums []int, k int) []int {",
      "\tfreq := make(map[int]int)",
      "\tfor _, n := range nums {",
      "\t\tfreq[n]++                       // count how often each value appears",
      "\t}",
      "\t// buckets[i] holds every value seen exactly i times; i never exceeds n",
      "\tbuckets := make([][]int, len(nums)+1)",
      "\tfor n, c := range freq {",
      "\t\tbuckets[c] = append(buckets[c], n)",
      "\t}",
      "\tout := []int{}",
      "\t// walk down from the highest possible count until we have k values",
      "\tfor c := len(buckets) - 1; c >= 0 && len(out) < k; c-- {",
      "\t\tout = append(out, buckets[c]...)",
      "\t}",
      "\tout = out[:k]",
      "\tsort.Ints(out)                      // map order is random in Go",
      "\treturn out",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(topKFrequent([]int{1, 1, 1, 2, 2, 3}, 2))",
      "}",
      "// bucket sort - O(n), beats a heap's O(n log k) here",
    ],
    expectedOutput: "[1 2]",
  },

  "climb-stairs-dp": {
    starter: "package main\n\nimport \"fmt\"\n\nfunc climbStairs(n int) int {\n\t// your code here\n\treturn 0\n}\n\nfunc main() {\n\tfmt.Println(climbStairs(5)) // 8\n}",
    solution: [
      "package main",
      "",
      "import \"fmt\"",
      "",
      "func climbStairs(n int) int {",
      "\t// step n is reached from n-1 (one step) or n-2 (two), so counts add",
      "\ta, b := 1, 1              // ways to stand at step 0 and step 1",
      "\tfor i := 2; i <= n; i++ {",
      "\t\ta, b = b, a+b         // slide the two-value window forward",
      "\t}",
      "\treturn b",
      "}",
      "",
      "func main() {",
      "\tfmt.Println(climbStairs(5))",
      "}",
      "// Fibonacci in disguise - O(n) time, O(1) space",
    ],
    expectedOutput: "8",
  },

  "url-shortener": {
    starter: "package main\n\nimport \"fmt\"\n\ntype UrlShortener struct {\n\t// your code here\n}\n\nfunc NewUrlShortener() *UrlShortener {\n\t// your code here\n\treturn &UrlShortener{}\n}\n\nfunc (s *UrlShortener) Shorten(url string) string {\n\t// your code here\n\treturn \"\"\n}\n\nfunc (s *UrlShortener) Expand(short string) string {\n\t// your code here\n\treturn \"\"\n}\n\nfunc main() {\n\ts := NewUrlShortener()\n\tshort := s.Shorten(\"https://example.com\")\n\tfmt.Println(short, s.Expand(short))\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"strings\"",
      ")",
      "",
      "const chars = \"abcdefghijklmnopqrstuvwxyz\" +",
      "\t\"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\"",
      "",
      "// turn a counter into a short slug - 62 symbols per character",
      "func base62(n int) string {",
      "\ts := \"\"",
      "\tfor {",
      "\t\ts = string(chars[n%62]) + s   // lowest base-62 digit first",
      "\t\tn /= 62                       // shift right one digit",
      "\t\tif n == 0 {",
      "\t\t\treturn s",
      "\t\t}",
      "\t}",
      "}",
      "",
      "type UrlShortener struct {",
      "\turls map[string]string          // slug -> url",
      "\tnext int                        // a counter, not a hash - no collisions",
      "}",
      "",
      "func NewUrlShortener() *UrlShortener {",
      "\treturn &UrlShortener{urls: make(map[string]string), next: 1}",
      "}",
      "",
      "func (s *UrlShortener) Shorten(url string) string {",
      "\tslug := base62(s.next)          // consume one counter value",
      "\ts.next++",
      "\ts.urls[slug] = url",
      "\treturn \"sho.rt/\" + slug",
      "}",
      "",
      "func (s *UrlShortener) Expand(short string) string {",
      "\t// accept a full short link or a bare slug",
      "\tparts := strings.Split(short, \"/\")",
      "\treturn s.urls[parts[len(parts)-1]]",
      "}",
      "",
      "func main() {",
      "\ts := NewUrlShortener()",
      "\tshort := s.Shorten(\"https://example.com\")",
      "\tfmt.Println(short, s.Expand(short))",
      "}",
      "// 7 chars of base62 is about 3.5 trillion ids",
    ],
    expectedOutput: "sho.rt/b https://example.com",
  },

  "sliding-window-limiter": {
    starter: "package main\n\nimport \"fmt\"\n\ntype SlidingWindowLimiter struct {\n\t// your code here\n}\n\nfunc NewSlidingWindowLimiter(limit int, windowMs int) *SlidingWindowLimiter {\n\t// your code here\n\treturn &SlidingWindowLimiter{}\n}\n\nfunc (l *SlidingWindowLimiter) Allow(key string) bool {\n\t// your code here\n\treturn false\n}\n\nfunc main() {\n\tl := NewSlidingWindowLimiter(2, 1000)\n\tfmt.Println(l.Allow(\"a\"), l.Allow(\"a\"), l.Allow(\"a\"))\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"time\"",
      ")",
      "",
      "type SlidingWindowLimiter struct {",
      "\tlimit int",
      "\twin   time.Duration",
      "\thits  map[string][]time.Time    // key -> timestamps of recent calls",
      "}",
      "",
      "func NewSlidingWindowLimiter(limit int, windowMs int) *SlidingWindowLimiter {",
      "\treturn &SlidingWindowLimiter{",
      "\t\tlimit: limit,",
      "\t\twin:   time.Duration(windowMs) * time.Millisecond,",
      "\t\thits:  make(map[string][]time.Time),",
      "\t}",
      "}",
      "",
      "func (l *SlidingWindowLimiter) Allow(key string) bool {",
      "\tnow := time.Now()",
      "\t// drop timestamps that aged out - this is what makes it \"sliding\"",
      "\tkept := l.hits[key][:0]",
      "\tfor _, t := range l.hits[key] {",
      "\t\tif now.Sub(t) < l.win {",
      "\t\t\tkept = append(kept, t)",
      "\t\t}",
      "\t}",
      "\tl.hits[key] = kept",
      "\tif len(kept) >= l.limit {",
      "\t\treturn false                 // budget already spent",
      "\t}",
      "\tl.hits[key] = append(kept, now)  // record this call",
      "\treturn true",
      "}",
      "",
      "func main() {",
      "\tl := NewSlidingWindowLimiter(2, 1000)",
      "\tfmt.Println(l.Allow(\"a\"), l.Allow(\"a\"), l.Allow(\"a\"))",
      "}",
      "// exact, but O(hits) memory - a token bucket scales better",
    ],
    expectedOutput: "true true false",
  },

  "throttle": {
    starter: "package main\n\nimport (\n\t\"fmt\"\n\t\"time\"\n)\n\nfunc throttle(wait time.Duration) func(func()) {\n\t// your code here\n\treturn func(fn func()) {}\n}\n\nfunc main() {\n\tn := 0\n\tcall := throttle(80 * time.Millisecond)\n\tcall(func() { n++ })\n\tcall(func() { n++ })\n\tcall(func() { n++ })\n\ttime.Sleep(250 * time.Millisecond)\n\tfmt.Println(n) // 2\n}",
    solution: [
      "package main",
      "",
      "import (",
      "\t\"fmt\"",
      "\t\"sync\"",
      "\t\"time\"",
      ")",
      "",
      "func throttle(wait time.Duration) func(func()) {",
      "\tvar mu sync.Mutex",
      "\tvar last time.Time",
      "\tpending := false",
      "\treturn func(fn func()) {",
      "\t\tmu.Lock()",
      "\t\tleft := wait - time.Since(last)",
      "\t\tif left <= 0 {              // window open - fire right away",
      "\t\t\tlast = time.Now()",
      "\t\t\tmu.Unlock()",
      "\t\t\tfn()",
      "\t\t\treturn",
      "\t\t}",
      "\t\tif pending {                // a trailing call is already queued",
      "\t\t\tmu.Unlock()",
      "\t\t\treturn",
      "\t\t}",
      "\t\tpending = true",
      "\t\tmu.Unlock()",
      "\t\ttime.AfterFunc(left, func() {",
      "\t\t\tmu.Lock()",
      "\t\t\tlast = time.Now()",
      "\t\t\tpending = false         // let the next burst queue again",
      "\t\t\tmu.Unlock()",
      "\t\t\tfn()",
      "\t\t})",
      "\t}",
      "}",
      "",
      "func main() {",
      "\tn := 0",
      "\tvar mu sync.Mutex",
      "\tcall := throttle(80 * time.Millisecond)",
      "\tbump := func() { mu.Lock(); n++; mu.Unlock() }",
      "\tcall(bump)",
      "\tcall(bump)",
      "\tcall(bump)",
      "\ttime.Sleep(250 * time.Millisecond)",
      "\tmu.Lock()",
      "\tfmt.Println(n)",
      "\tmu.Unlock()",
      "}",
      "// leading + trailing edge: a burst produces exactly two calls",
    ],
    expectedOutput: "2",
  },
};
