import type { LangTable } from "./index";

export const JAVA: LangTable = {
  "two-sum": {
    starter: "import java.util.*;\n\npublic class Main {\n    static int[] twoSum(int[] nums, int target) {\n        // your code here\n        return new int[]{};\n    }\n\n    public static void main(String[] args) {\n        System.out.println(Arrays.toString(twoSum(new int[]{2, 7, 11, 15}, 9)));  // [0, 1]\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static int[] twoSum(int[] nums, int target) {",
      "        Map<Integer, Integer> seen = new HashMap<>();      // value -> its index",
      "        for (int i = 0; i < nums.length; i++) {",
      "            int need = target - nums[i];                   // the partner we want",
      "            if (seen.containsKey(need))                    // met it already?",
      "                return new int[]{seen.get(need), i};",
      "            seen.put(nums[i], i);                          // remember for later",
      "        }",
      "        return new int[]{};                                // promised unreachable",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(Arrays.toString(twoSum(new int[]{2, 7, 11, 15}, 9)));",
      "    }",
      "}",
      "// O(n) time, O(n) space - one pass, O(1) HashMap lookups",
    ],
    expectedOutput: "[0, 1]",
  },

  "max-subarray": {
    starter: "public class Main {\n    static int maxSubArray(int[] nums) {\n        // your code here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(maxSubArray(new int[]{-2, 1, -3, 4, -1, 2, 1, -5, 4}));  // 6\n    }\n}",
    solution: [
      "public class Main {",
      "    static int maxSubArray(int[] nums) {",
      "        int best = nums[0], cur = nums[0];        // both start on element 0",
      "        for (int i = 1; i < nums.length; i++) {",
      "            // extending only helps if the run so far is not dragging us down",
      "            cur = Math.max(nums[i], cur + nums[i]);",
      "            best = Math.max(best, cur);           // remember the best run seen",
      "        }",
      "        return best;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(maxSubArray(new int[]{-2, 1, -3, 4, -1, 2, 1, -5, 4}));",
      "    }",
      "}",
      "// Kadane's algorithm - O(n) time, O(1) space",
    ],
    expectedOutput: "6",
  },

  "valid-parens": {
    starter: "import java.util.*;\n\npublic class Main {\n    static boolean isValid(String s) {\n        // your code here\n        return false;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(isValid(\"()[]{}\"));  // true\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static boolean isValid(String s) {",
      "        Map<Character, Character> pairs = new HashMap<>();",
      "        pairs.put(')', '(');                       // closer -> its opener",
      "        pairs.put(']', '[');",
      "        pairs.put('}', '{');",
      "        Deque<Character> stack = new ArrayDeque<>();",
      "        for (char ch : s.toCharArray()) {",
      "            if (!pairs.containsKey(ch)) {          // an opener: remember it",
      "                stack.push(ch);",
      "                continue;",
      "            }",
      "            // a closer must match the most recent unclosed opener",
      "            if (stack.isEmpty() || stack.pop() != pairs.get(ch)) return false;",
      "        }",
      "        return stack.isEmpty();                    // anything left open is invalid",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(isValid(\"()[]{}\"));",
      "    }",
      "}",
      "// O(n) time, O(n) space",
    ],
    expectedOutput: "true",
  },

  lru: {
    starter: "import java.util.*;\n\npublic class Main {\n    static class LRUCache {\n        LRUCache(int cap) {\n            // your code here\n        }\n\n        int get(int k) {\n            // your code here\n            return -1;\n        }\n\n        void put(int k, int v) {\n            // your code here\n        }\n    }\n\n    public static void main(String[] args) {\n        LRUCache c = new LRUCache(2);\n        c.put(1, 1);\n        c.put(2, 2);\n        System.out.println(c.get(1));  // 1\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static class LRUCache {",
      "        private final int cap;",
      "        private final LinkedHashMap<Integer, Integer> m;",
      "",
      "        LRUCache(int cap) {",
      "            this.cap = cap;",
      "            // accessOrder=true makes get() move an entry to the end for us",
      "            this.m = new LinkedHashMap<>(16, 0.75f, true);",
      "        }",
      "",
      "        int get(int k) {",
      "            return m.getOrDefault(k, -1);     // access reorders automatically",
      "        }",
      "",
      "        void put(int k, int v) {",
      "            m.put(k, v);                      // insert or refresh",
      "            if (m.size() > cap) {",
      "                // iteration order is least-recently-used first",
      "                Iterator<Integer> it = m.keySet().iterator();",
      "                it.next();",
      "                it.remove();",
      "            }",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        LRUCache c = new LRUCache(2);",
      "        c.put(1, 1);",
      "        c.put(2, 2);",
      "        System.out.println(c.get(1));",
      "        c.put(3, 3);",
      "        System.out.println(c.get(2));",
      "    }",
      "}",
      "// O(1) get and put - LinkedHashMap does the ordering",
    ],
    expectedOutput: "1\n-1",
  },

  "rate-limiter": {
    starter: "public class Main {\n    static class RateLimiter {\n        RateLimiter(double rate, double per) {\n            // your code here\n        }\n\n        boolean allow() {\n            // your code here\n            return false;\n        }\n    }\n\n    public static void main(String[] args) {\n        RateLimiter r = new RateLimiter(2, 1000);\n        System.out.println(r.allow() + \", \" + r.allow() + \", \" + r.allow());\n    }\n}",
    solution: [
      "public class Main {",
      "    static class RateLimiter {",
      "        private final double rate, per;",
      "        private double tokens;",
      "        private long last;",
      "",
      "        RateLimiter(double rate, double per) {",
      "            this.rate = rate;                 // bucket size = biggest burst",
      "            this.per = per;                   // ms for a full refill",
      "            this.tokens = rate;               // start full",
      "            this.last = System.currentTimeMillis();",
      "        }",
      "",
      "        boolean allow() {",
      "            long now = System.currentTimeMillis();",
      "            // refill continuously: elapsed/per is the fraction of a bucket earned",
      "            tokens += ((now - last) / per) * rate;",
      "            tokens = Math.min(tokens, rate);  // never over-fill",
      "            last = now;",
      "            if (tokens < 1) return false;     // not even one whole token",
      "            tokens -= 1;                      // spend it",
      "            return true;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        RateLimiter r = new RateLimiter(2, 1000);",
      "        System.out.println(r.allow() + \", \" + r.allow() + \", \" + r.allow());",
      "    }",
      "}",
      "// O(1) time and memory - no request history is kept",
    ],
    expectedOutput: "true, true, false",
  },

  debounce: {
    starter: "import java.util.concurrent.*;\n\npublic class Main {\n    static class Debouncer {\n        Debouncer(long waitMs) {\n            // your code here\n        }\n\n        void call(Runnable fn) {\n            // your code here\n        }\n\n        void shutdown() {\n            // your code here\n        }\n    }\n\n    public static void main(String[] args) throws Exception {\n        int[] n = {0};\n        Debouncer d = new Debouncer(50);\n        d.call(() -> n[0]++);\n        d.call(() -> n[0]++);\n        Thread.sleep(200);\n        System.out.println(n[0]);  // 1\n        d.shutdown();\n    }\n}",
    solution: [
      "import java.util.concurrent.*;",
      "",
      "public class Main {",
      "    static class Debouncer {",
      "        private final ScheduledExecutorService pool =",
      "            Executors.newSingleThreadScheduledExecutor();",
      "        private final long waitMs;",
      "        private ScheduledFuture<?> pending;   // the queued call, if any",
      "",
      "        Debouncer(long waitMs) {",
      "            this.waitMs = waitMs;",
      "        }",
      "",
      "        synchronized void call(Runnable fn) {",
      "            if (pending != null) pending.cancel(false);   // a new call cancels the old",
      "            // only the final call of a burst survives long enough to run",
      "            pending = pool.schedule(fn, waitMs, TimeUnit.MILLISECONDS);",
      "        }",
      "",
      "        void shutdown() {",
      "            pool.shutdown();",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        int[] n = {0};",
      "        Debouncer d = new Debouncer(50);",
      "        d.call(() -> n[0]++);",
      "        d.call(() -> n[0]++);",
      "        d.call(() -> n[0]++);",
      "        Thread.sleep(200);",
      "        System.out.println(n[0]);",
      "        d.shutdown();",
      "    }",
      "}",
      "// every call restarts the clock, so fn runs once the calls stop",
    ],
    expectedOutput: "1",
  },

  "binary-search": {
    starter: "public class Main {\n    static int search(int[] nums, int target) {\n        // your code here\n        return -1;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(search(new int[]{-1, 0, 3, 5, 9, 12}, 9));  // 4\n    }\n}",
    solution: [
      "public class Main {",
      "    static int search(int[] nums, int target) {",
      "        int lo = 0, hi = nums.length - 1;         // inclusive bounds",
      "        while (lo <= hi) {",
      "            int mid = (lo + hi) >>> 1;            // unsigned shift avoids overflow",
      "            if (nums[mid] == target) return mid;",
      "            if (nums[mid] < target) lo = mid + 1; // answer lies to the right",
      "            else hi = mid - 1;                    // answer lies to the left",
      "        }",
      "        return -1;                                // bounds crossed - not present",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(search(new int[]{-1, 0, 3, 5, 9, 12}, 9));",
      "    }",
      "}",
      "// O(log n) - the range halves every iteration",
    ],
    expectedOutput: "4",
  },

  "promise-pool": {
    starter: "import java.util.*;\nimport java.util.concurrent.*;\n\npublic class Main {\n    static <T> List<T> pool(List<Callable<T>> tasks, int limit) throws Exception {\n        // your code here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) throws Exception {\n        List<Callable<Integer>> tasks = Arrays.asList(() -> 1, () -> 2, () -> 3);\n        System.out.println(pool(tasks, 2));  // [1, 2, 3]\n    }\n}",
    solution: [
      "import java.util.*;",
      "import java.util.concurrent.*;",
      "",
      "public class Main {",
      "    static <T> List<T> pool(List<Callable<T>> tasks, int limit) throws Exception {",
      "        // a fixed pool IS the concurrency limit - at most `limit` threads run",
      "        ExecutorService ex = Executors.newFixedThreadPool(limit);",
      "        List<Future<T>> futures = new ArrayList<>();",
      "        for (Callable<T> t : tasks) futures.add(ex.submit(t));   // queue them all",
      "        List<T> out = new ArrayList<>();",
      "        // collecting in submission order restores the input ordering",
      "        for (Future<T> f : futures) out.add(f.get());",
      "        ex.shutdown();",
      "        return out;",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        List<Callable<Integer>> tasks = Arrays.asList(() -> 1, () -> 2, () -> 3);",
      "        System.out.println(pool(tasks, 2));",
      "    }",
      "}",
      "// exactly `limit` run at once, results keep their input order",
    ],
    expectedOutput: "[1, 2, 3]",
  },

  "group-anagrams": {
    starter: "import java.util.*;\n\npublic class Main {\n    static List<List<String>> groupAnagrams(String[] strs) {\n        // your code here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        System.out.println(groupAnagrams(new String[]{\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"}));\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static List<List<String>> groupAnagrams(String[] strs) {",
      "        Map<String, List<String>> groups = new LinkedHashMap<>();",
      "        for (String w : strs) {",
      "            char[] c = w.toCharArray();",
      "            Arrays.sort(c);                    // anagrams share sorted letters",
      "            String key = new String(c);        // so that is a stable group key",
      "            groups.computeIfAbsent(key, k -> new ArrayList<>()).add(w);",
      "        }",
      "        return new ArrayList<>(groups.values());",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(groupAnagrams(new String[]{\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"}));",
      "    }",
      "}",
      "// O(n * k log k) for n words of length k",
    ],
    expectedOutput: "[[eat, tea, ate], [tan, nat], [bat]]",
  },

  flatten: {
    starter: "import java.util.*;\n\npublic class Main {\n    static List<Object> flatten(List<Object> arr) {\n        // your code here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        List<Object> nested = Arrays.asList(1, Arrays.asList(2, Arrays.asList(3, Arrays.asList(4))));\n        System.out.println(flatten(nested));  // [1, 2, 3, 4]\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    @SuppressWarnings(\"unchecked\")",
      "    static List<Object> flatten(List<Object> arr) {",
      "        List<Object> out = new ArrayList<>();",
      "        for (Object x : arr) {",
      "            // recurse into nested lists, keep every other value as it is",
      "            if (x instanceof List) out.addAll(flatten((List<Object>) x));",
      "            else out.add(x);",
      "        }",
      "        return out;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        List<Object> nested = Arrays.asList(1, Arrays.asList(2, Arrays.asList(3, Arrays.asList(4))));",
      "        System.out.println(flatten(nested));",
      "    }",
      "}",
      "// visits every element once - O(total elements)",
    ],
    expectedOutput: "[1, 2, 3, 4]",
  },

  "longest-unique-substring": {
    starter: "import java.util.*;\n\npublic class Main {\n    static int lengthOfLongestSubstring(String s) {\n        // your code here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(lengthOfLongestSubstring(\"abcabcbb\"));  // 3\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static int lengthOfLongestSubstring(String s) {",
      "        Map<Character, Integer> seen = new HashMap<>();   // char -> last index",
      "        int best = 0, start = 0;                          // start = window's left edge",
      "        for (int i = 0; i < s.length(); i++) {",
      "            char ch = s.charAt(i);",
      "            Integer prev = seen.get(ch);",
      "            // only move the window forward, never back past `start`",
      "            if (prev != null && prev >= start) start = prev + 1;",
      "            seen.put(ch, i);",
      "            best = Math.max(best, i - start + 1);         // window size",
      "        }",
      "        return best;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(lengthOfLongestSubstring(\"abcabcbb\"));",
      "    }",
      "}",
      "// sliding window - O(n), each character handled once",
    ],
    expectedOutput: "3",
  },

  "merge-intervals": {
    starter: "import java.util.*;\n\npublic class Main {\n    static int[][] merge(int[][] intervals) {\n        // your code here\n        return new int[][]{};\n    }\n\n    public static void main(String[] args) {\n        System.out.println(Arrays.deepToString(merge(new int[][]{{1, 3}, {2, 6}, {8, 10}, {15, 18}})));\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static int[][] merge(int[][] intervals) {",
      "        // sort by start so any overlaps end up next to each other",
      "        Arrays.sort(intervals, (a, b) -> Integer.compare(a[0], b[0]));",
      "        List<int[]> out = new ArrayList<>();",
      "        for (int[] iv : intervals) {",
      "            int[] last = out.isEmpty() ? null : out.get(out.size() - 1);",
      "            // starts before the previous one ended -> overlap, so stretch it",
      "            if (last != null && iv[0] <= last[1]) last[1] = Math.max(last[1], iv[1]);",
      "            else out.add(new int[]{iv[0], iv[1]});     // no overlap: new range",
      "        }",
      "        return out.toArray(new int[0][]);",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(Arrays.deepToString(merge(new int[][]{{1, 3}, {2, 6}, {8, 10}, {15, 18}})));",
      "    }",
      "}",
      "// O(n log n), dominated by the sort",
    ],
    expectedOutput: "[[1, 6], [8, 10], [15, 18]]",
  },

  "reverse-list": {
    starter: "public class Main {\n    static class Node {\n        int val;\n        Node next;\n        Node(int val, Node next) { this.val = val; this.next = next; }\n    }\n\n    static Node reverseList(Node head) {\n        // your code here\n        return null;\n    }\n\n    public static void main(String[] args) {\n        Node head = new Node(1, new Node(2, new Node(3, null)));\n        StringBuilder sb = new StringBuilder(\"[\");\n        for (Node r = reverseList(head); r != null; r = r.next) {\n            sb.append(r.val);\n            if (r.next != null) sb.append(\", \");\n        }\n        System.out.println(sb.append(\"]\"));  // [3, 2, 1]\n    }\n}",
    solution: [
      "public class Main {",
      "    static class Node {",
      "        int val;",
      "        Node next;",
      "        Node(int val, Node next) { this.val = val; this.next = next; }",
      "    }",
      "",
      "    static Node reverseList(Node head) {",
      "        Node prev = null, cur = head;",
      "        while (cur != null) {",
      "            Node next = cur.next;   // save the rest before overwriting the link",
      "            cur.next = prev;        // point this node backwards",
      "            prev = cur;             // prev follows cur forward",
      "            cur = next;             // carry on down the original list",
      "        }",
      "        return prev;                // cur is null, so prev is the new head",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        Node head = new Node(1, new Node(2, new Node(3, null)));",
      "        StringBuilder sb = new StringBuilder(\"[\");",
      "        for (Node r = reverseList(head); r != null; r = r.next) {",
      "            sb.append(r.val);",
      "            if (r.next != null) sb.append(\", \");",
      "        }",
      "        System.out.println(sb.append(\"]\"));",
      "    }",
      "}",
      "// O(n) time, O(1) space - three pointers, no new nodes",
    ],
    expectedOutput: "[3, 2, 1]",
  },

  "search-rotated": {
    starter: "public class Main {\n    static int searchRotated(int[] nums, int target) {\n        // your code here\n        return -1;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(searchRotated(new int[]{4, 5, 6, 7, 0, 1, 2}, 0));  // 4\n    }\n}",
    solution: [
      "public class Main {",
      "    static int searchRotated(int[] nums, int target) {",
      "        int lo = 0, hi = nums.length - 1;",
      "        while (lo <= hi) {",
      "            int mid = (lo + hi) >>> 1;",
      "            if (nums[mid] == target) return mid;",
      "            // whatever the rotation, one side of mid is always sorted",
      "            if (nums[lo] <= nums[mid]) {              // left half is sorted",
      "                // inside that range? search it, otherwise take the other half",
      "                if (nums[lo] <= target && target < nums[mid]) hi = mid - 1;",
      "                else lo = mid + 1;",
      "            } else {                                  // right half is sorted",
      "                if (nums[mid] < target && target <= nums[hi]) lo = mid + 1;",
      "                else hi = mid - 1;",
      "            }",
      "        }",
      "        return -1;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(searchRotated(new int[]{4, 5, 6, 7, 0, 1, 2}, 0));",
      "    }",
      "}",
      "// still O(log n) - one comparison discards half the range",
    ],
    expectedOutput: "4",
  },

  "num-islands-dfs": {
    starter: "public class Main {\n    static int numIslands(char[][] grid) {\n        // your code here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        char[][] grid = {\n            {'1', '1', '0'},\n            {'1', '1', '0'},\n            {'0', '0', '0'},\n        };\n        System.out.println(numIslands(grid));  // 1\n    }\n}",
    solution: [
      "public class Main {",
      "    static int numIslands(char[][] grid) {",
      "        int count = 0;",
      "        for (int r = 0; r < grid.length; r++)",
      "            for (int c = 0; c < grid[0].length; c++)",
      "                // each land cell still standing begins exactly one new island",
      "                if (grid[r][c] == '1') { count++; sink(grid, r, c); }",
      "        return count;",
      "    }",
      "",
      "    // flood fill: sink every cell of an island so it is counted only once",
      "    static void sink(char[][] grid, int r, int c) {",
      "        if (r < 0 || c < 0 || r >= grid.length) return;   // off vertically",
      "        if (c >= grid[0].length) return;                  // off the right edge",
      "        if (grid[r][c] != '1') return;                    // water or already sunk",
      "        grid[r][c] = '0';                                 // mark visited",
      "        sink(grid, r + 1, c); sink(grid, r - 1, c);       // spread vertically",
      "        sink(grid, r, c + 1); sink(grid, r, c - 1);       // and horizontally",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        char[][] grid = {",
      "            {'1', '1', '0'},",
      "            {'1', '1', '0'},",
      "            {'0', '0', '0'},",
      "        };",
      "        System.out.println(numIslands(grid));",
      "    }",
      "}",
      "// O(rows * cols) - each cell is touched a constant number of times",
    ],
    expectedOutput: "1",
  },

  "top-k-frequent-bucket": {
    starter: "import java.util.*;\n\npublic class Main {\n    static List<Integer> topKFrequent(int[] nums, int k) {\n        // your code here\n        return new ArrayList<>();\n    }\n\n    public static void main(String[] args) {\n        List<Integer> r = new ArrayList<>(topKFrequent(new int[]{1, 1, 1, 2, 2, 3}, 2));\n        Collections.sort(r);\n        System.out.println(r);  // [1, 2]\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static List<Integer> topKFrequent(int[] nums, int k) {",
      "        Map<Integer, Integer> freq = new HashMap<>();",
      "        for (int n : nums) freq.merge(n, 1, Integer::sum);   // count each value",
      "        // buckets[i] holds every value seen exactly i times; i never exceeds n",
      "        List<List<Integer>> buckets = new ArrayList<>();",
      "        for (int i = 0; i <= nums.length; i++) buckets.add(new ArrayList<>());",
      "        for (Map.Entry<Integer, Integer> e : freq.entrySet())",
      "            buckets.get(e.getValue()).add(e.getKey());",
      "        List<Integer> out = new ArrayList<>();",
      "        // walk down from the highest possible count until we have k values",
      "        for (int c = buckets.size() - 1; c >= 0 && out.size() < k; c--)",
      "            out.addAll(buckets.get(c));",
      "        return out.subList(0, Math.min(k, out.size()));      // trim any overshoot",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        List<Integer> r = new ArrayList<>(topKFrequent(new int[]{1, 1, 1, 2, 2, 3}, 2));",
      "        Collections.sort(r);",
      "        System.out.println(r);",
      "    }",
      "}",
      "// bucket sort - O(n), beats a heap's O(n log k) here",
    ],
    expectedOutput: "[1, 2]",
  },

  "climb-stairs-dp": {
    starter: "public class Main {\n    static int climbStairs(int n) {\n        // your code here\n        return 0;\n    }\n\n    public static void main(String[] args) {\n        System.out.println(climbStairs(5));  // 8\n    }\n}",
    solution: [
      "public class Main {",
      "    static int climbStairs(int n) {",
      "        // step n is reached from n-1 (one step) or n-2 (two), so counts add",
      "        int a = 1, b = 1;                 // ways to stand at step 0 and step 1",
      "        for (int i = 2; i <= n; i++) {",
      "            int next = a + b;             // slide the two-value window forward",
      "            a = b;",
      "            b = next;",
      "        }",
      "        return b;",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        System.out.println(climbStairs(5));",
      "    }",
      "}",
      "// Fibonacci in disguise - O(n) time, O(1) space",
    ],
    expectedOutput: "8",
  },

  "url-shortener": {
    starter: "import java.util.*;\n\npublic class Main {\n    static class UrlShortener {\n        UrlShortener() {\n            // your code here\n        }\n\n        String shorten(String url) {\n            // your code here\n            return \"\";\n        }\n\n        String expand(String shortUrl) {\n            // your code here\n            return null;\n        }\n    }\n\n    public static void main(String[] args) {\n        UrlShortener s = new UrlShortener();\n        String shortUrl = s.shorten(\"https://example.com\");\n        System.out.println(shortUrl + \" \" + s.expand(shortUrl));\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static final String CHARS =",
      "        \"abcdefghijklmnopqrstuvwxyz\" +",
      "        \"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\";",
      "",
      "    // turn a counter into a short slug - 62 symbols per character",
      "    static String base62(long n) {",
      "        StringBuilder s = new StringBuilder();",
      "        do {",
      "            s.insert(0, CHARS.charAt((int) (n % 62)));  // lowest digit first",
      "            n /= 62;                                    // shift right one digit",
      "        } while (n > 0);",
      "        return s.toString();",
      "    }",
      "",
      "    static class UrlShortener {",
      "        private final Map<String, String> urls = new HashMap<>();  // slug -> url",
      "        private long next = 1;    // a counter, not a hash - so slugs never collide",
      "",
      "        String shorten(String url) {",
      "            String slug = base62(next++);      // consume one counter value",
      "            urls.put(slug, url);",
      "            return \"sho.rt/\" + slug;",
      "        }",
      "",
      "        String expand(String shortUrl) {",
      "            // accept a full short link or a bare slug",
      "            String[] parts = shortUrl.split(\"/\");",
      "            return urls.get(parts[parts.length - 1]);",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        UrlShortener s = new UrlShortener();",
      "        String shortUrl = s.shorten(\"https://example.com\");",
      "        System.out.println(shortUrl + \" \" + s.expand(shortUrl));",
      "    }",
      "}",
      "// 7 chars of base62 is about 3.5 trillion ids",
    ],
    expectedOutput: "sho.rt/b https://example.com",
  },

  "sliding-window-limiter": {
    starter: "import java.util.*;\n\npublic class Main {\n    static class SlidingWindowLimiter {\n        SlidingWindowLimiter(int limit, long windowMs) {\n            // your code here\n        }\n\n        boolean allow(String key) {\n            // your code here\n            return false;\n        }\n    }\n\n    public static void main(String[] args) {\n        SlidingWindowLimiter l = new SlidingWindowLimiter(2, 1000);\n        System.out.println(l.allow(\"a\") + \", \" + l.allow(\"a\") + \", \" + l.allow(\"a\"));\n    }\n}",
    solution: [
      "import java.util.*;",
      "",
      "public class Main {",
      "    static class SlidingWindowLimiter {",
      "        private final int limit;",
      "        private final long win;",
      "        private final Map<String, List<Long>> hits = new HashMap<>();  // key -> times",
      "",
      "        SlidingWindowLimiter(int limit, long windowMs) {",
      "            this.limit = limit;",
      "            this.win = windowMs;",
      "        }",
      "",
      "        boolean allow(String key) {",
      "            long now = System.currentTimeMillis();",
      "            List<Long> log = hits.computeIfAbsent(key, k -> new ArrayList<>());",
      "            // drop timestamps that aged out - this is what makes it \"sliding\"",
      "            log.removeIf(t -> now - t >= win);",
      "            if (log.size() >= limit) return false;   // budget already spent",
      "            log.add(now);                            // record this call",
      "            return true;",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) {",
      "        SlidingWindowLimiter l = new SlidingWindowLimiter(2, 1000);",
      "        System.out.println(l.allow(\"a\") + \", \" + l.allow(\"a\") + \", \" + l.allow(\"a\"));",
      "    }",
      "}",
      "// exact, but O(hits) memory - a token bucket scales better",
    ],
    expectedOutput: "true, true, false",
  },

  throttle: {
    starter: "import java.util.concurrent.*;\n\npublic class Main {\n    static class Throttler {\n        Throttler(long waitMs) {\n            // your code here\n        }\n\n        void call(Runnable fn) {\n            // your code here\n        }\n\n        void shutdown() {\n            // your code here\n        }\n    }\n\n    public static void main(String[] args) throws Exception {\n        int[] n = {0};\n        Throttler t = new Throttler(80);\n        t.call(() -> n[0]++);\n        t.call(() -> n[0]++);\n        t.call(() -> n[0]++);\n        Thread.sleep(250);\n        System.out.println(n[0]);  // 2\n        t.shutdown();\n    }\n}",
    solution: [
      "import java.util.concurrent.*;",
      "",
      "public class Main {",
      "    static class Throttler {",
      "        private final ScheduledExecutorService pool =",
      "            Executors.newSingleThreadScheduledExecutor();",
      "        private final long waitMs;",
      "        private long last = 0;                // when fn last ran",
      "        private ScheduledFuture<?> pending;   // the queued trailing call",
      "",
      "        Throttler(long waitMs) {",
      "            this.waitMs = waitMs;",
      "        }",
      "",
      "        synchronized void call(Runnable fn) {",
      "            long now = System.currentTimeMillis();",
      "            long left = waitMs - (now - last);    // ms until the window reopens",
      "            if (left <= 0) {                      // window open - fire right away",
      "                last = now;",
      "                fn.run();",
      "            } else if (pending == null) {         // closed - queue ONE trailing call",
      "                pending = pool.schedule(() -> {",
      "                    synchronized (this) {",
      "                        last = System.currentTimeMillis();",
      "                        pending = null;           // let the next burst queue again",
      "                    }",
      "                    fn.run();",
      "                }, left, TimeUnit.MILLISECONDS);",
      "            }",
      "            // further calls while a timer is pending are simply dropped",
      "        }",
      "",
      "        void shutdown() {",
      "            pool.shutdown();",
      "        }",
      "    }",
      "",
      "    public static void main(String[] args) throws Exception {",
      "        int[] n = {0};",
      "        Throttler t = new Throttler(80);",
      "        t.call(() -> n[0]++);",
      "        t.call(() -> n[0]++);",
      "        t.call(() -> n[0]++);",
      "        Thread.sleep(250);",
      "        System.out.println(n[0]);",
      "        t.shutdown();",
      "    }",
      "}",
      "// leading + trailing edge: a burst produces exactly two calls",
    ],
    expectedOutput: "2",
  },
};
