import type { LangTable } from "./index";

// PHP starters and reference solutions. Each entry opens with <?php and echoes
// a result. Runs on Judge0 language id 98 (PHP 8.3.11).
export const PHP: LangTable = {
  "two-sum": {
    starter: "<?php\nfunction twoSum(array $nums, int $target): array {\n    // your code here\n    return [];\n}\n\nprint_r(twoSum([2, 7, 11, 15], 9));",
    solution: [
      "<?php",
      "function twoSum(array $nums, int $target): array {",
      "    $seen = [];                          // value => its index",
      "    foreach ($nums as $i => $n) {",
      "        $need = $target - $n;            // the partner we want",
      "        if (isset($seen[$need])) {       // met it already?",
      "            return [$seen[$need], $i];",
      "        }",
      "        $seen[$n] = $i;                  // remember for later",
      "    }",
      "    return [];",
      "}",
      "",
      "echo implode(\" \", twoSum([2, 7, 11, 15], 9)), \"\\n\";",
      "// O(n) time, O(n) space - one pass, O(1) hash lookups",
    ],
    expectedOutput: "0 1",
  },

  "max-subarray": {
    starter: "<?php\nfunction maxSubArray(array $nums): int {\n    // your code here\n    return 0;\n}\n\necho maxSubArray([-2, 1, -3, 4, -1, 2, 1, -5, 4]), \"\\n\";  // 6",
    solution: [
      "<?php",
      "function maxSubArray(array $nums): int {",
      "    $best = $cur = $nums[0];             // both start on element 0",
      "    for ($i = 1; $i < count($nums); $i++) {",
      "        // extending only helps if the run so far is not dragging us down",
      "        $cur = max($nums[$i], $cur + $nums[$i]);",
      "        $best = max($best, $cur);        // remember the best run seen",
      "    }",
      "    return $best;",
      "}",
      "",
      "echo maxSubArray([-2, 1, -3, 4, -1, 2, 1, -5, 4]), \"\\n\";",
      "// Kadane's algorithm - O(n) time, O(1) space",
    ],
    expectedOutput: "6",
  },

  "valid-parens": {
    starter: "<?php\nfunction isValid(string $s): bool {\n    // your code here\n    return false;\n}\n\necho isValid(\"()[]{}\") ? \"true\" : \"false\", \"\\n\";",
    solution: [
      "<?php",
      "function isValid(string $s): bool {",
      "    $pairs = [\")\" => \"(\", \"]\" => \"[\", \"}\" => \"{\"];  // closer => its opener",
      "    $stack = [];",
      "    foreach (str_split($s) as $ch) {",
      "        if (!isset($pairs[$ch])) {       // an opener: remember it",
      "            $stack[] = $ch;",
      "            continue;",
      "        }",
      "        // a closer must match the most recent unclosed opener",
      "        if (array_pop($stack) !== $pairs[$ch]) {",
      "            return false;",
      "        }",
      "    }",
      "    return count($stack) === 0;          // anything left open is invalid",
      "}",
      "",
      "echo isValid(\"()[]{}\") ? \"true\" : \"false\", \"\\n\";",
      "// O(n) time, O(n) space",
    ],
    expectedOutput: "true",
  },

  "lru": {
    starter: "<?php\nclass LRUCache {\n    public function __construct(private int $cap) {\n        // your code here\n    }\n\n    public function get(int $k): int {\n        // your code here\n        return -1;\n    }\n\n    public function put(int $k, int $v): void {\n        // your code here\n    }\n}\n\n$c = new LRUCache(2);\n$c->put(1, 1);\n$c->put(2, 2);\necho $c->get(1), \"\\n\";  // 1",
    solution: [
      "<?php",
      "class LRUCache {",
      "    private array $m = [];               // PHP arrays preserve insertion order",
      "",
      "    public function __construct(private int $cap) {}",
      "",
      "    public function get(int $k): int {",
      "        if (!array_key_exists($k, $this->m)) {",
      "            return -1;                   // miss",
      "        }",
      "        $v = $this->m[$k];",
      "        unset($this->m[$k]);             // unset + re-set moves it to the end,",
      "        $this->m[$k] = $v;               // which marks it most-recently-used",
      "        return $v;",
      "    }",
      "",
      "    public function put(int $k, int $v): void {",
      "        if (array_key_exists($k, $this->m)) {",
      "            unset($this->m[$k]);         // drop the old position first",
      "        }",
      "        $this->m[$k] = $v;               // re-insert at the end = most recent",
      "        if (count($this->m) > $this->cap) {",
      "            // the first key in order is the least recently used",
      "            array_shift($this->m);",
      "        }",
      "    }",
      "}",
      "",
      "$c = new LRUCache(2);",
      "$c->put(1, 1);",
      "$c->put(2, 2);",
      "echo $c->get(1), \"\\n\";",
      "$c->put(3, 3);",
      "echo $c->get(2), \"\\n\";",
      "// O(1) get and put - array ordering does the bookkeeping",
    ],
    expectedOutput: "1\n-1",
  },

  "rate-limiter": {
    starter: "<?php\nclass RateLimiter {\n    public function __construct(private float $rate, private float $per) {\n        // your code here\n    }\n\n    public function allow(): bool {\n        // your code here\n        return false;\n    }\n}\n\n$r = new RateLimiter(2, 1000);\necho implode(\" \", [var_export($r->allow(), true), var_export($r->allow(), true), var_export($r->allow(), true)]), \"\\n\";",
    solution: [
      "<?php",
      "class RateLimiter {",
      "    private float $tokens;",
      "    private float $last;",
      "",
      "    public function __construct(private float $rate, private float $per) {",
      "        $this->tokens = $rate;           // start full: a burst works immediately",
      "        $this->last = microtime(true) * 1000;",
      "    }",
      "",
      "    public function allow(): bool {",
      "        $now = microtime(true) * 1000;",
      "        // refill continuously: elapsed/per is the fraction of a bucket earned",
      "        $this->tokens += (($now - $this->last) / $this->per) * $this->rate;",
      "        $this->tokens = min($this->tokens, $this->rate);   // never over-fill",
      "        $this->last = $now;",
      "        if ($this->tokens < 1) {",
      "            return false;                // not even one whole token",
      "        }",
      "        $this->tokens -= 1;              // spend it",
      "        return true;",
      "    }",
      "}",
      "",
      "$r = new RateLimiter(2, 1000);",
      "$out = [];",
      "foreach ([1, 2, 3] as $_) {",
      "    $out[] = $r->allow() ? \"true\" : \"false\";",
      "}",
      "echo implode(\" \", $out), \"\\n\";",
      "// O(1) time and memory - no request history is kept",
    ],
    expectedOutput: "true true false",
  },

  "debounce": {
    starter: "<?php\n// PHP runs synchronously with no event loop, so debounce is modelled as\n// \"collapse a burst into the last call\", flushed explicitly.\nclass Debouncer {\n    public function __construct(private $fn, private float $waitMs) {\n        // your code here\n    }\n\n    public function call(...$args): void {\n        // your code here\n    }\n\n    public function flush(): void {\n        // your code here\n    }\n}\n\n$calls = [];\n$d = new Debouncer(function ($v) use (&$calls) { $calls[] = $v; }, 50);\n$d->call(\"a\");\n$d->call(\"b\");\n$d->flush();\necho implode(\" \", $calls), \"\\n\";  // b",
    solution: [
      "<?php",
      "// PHP runs a single synchronous request, so there is no event loop to defer to.",
      "// Debounce is modelled as \"collapse a burst into the last call\", flushed",
      "// explicitly - the semantics that survive translation from JavaScript.",
      "class Debouncer {",
      "    private $pending = null;             // the newest queued arguments",
      "",
      "    public function __construct(private $fn, private float $waitMs) {}",
      "",
      "    public function call(...$args): void {",
      "        $this->pending = $args;          // each call replaces the previous one",
      "    }",
      "",
      "    public function flush(): void {",
      "        if ($this->pending !== null) {   // only the last call survives",
      "            ($this->fn)(...$this->pending);",
      "            $this->pending = null;",
      "        }",
      "    }",
      "}",
      "",
      "$calls = [];",
      "$d = new Debouncer(function ($v) use (&$calls) { $calls[] = $v; }, 50);",
      "$d->call(\"a\");",
      "$d->call(\"b\");",
      "$d->call(\"c\");",
      "$d->flush();",
      "echo implode(\" \", $calls), \"\\n\";",
      "// one call survives the burst, carrying the last arguments",
    ],
    expectedOutput: "c",
  },

  "binary-search": {
    starter: "<?php\nfunction search(array $nums, int $target): int {\n    // your code here\n    return -1;\n}\n\necho search([-1, 0, 3, 5, 9, 12], 9), \"\\n\";  // 4",
    solution: [
      "<?php",
      "function search(array $nums, int $target): int {",
      "    $lo = 0;",
      "    $hi = count($nums) - 1;              // inclusive bounds",
      "    while ($lo <= $hi) {",
      "        $mid = intdiv($lo + $hi, 2);",
      "        if ($nums[$mid] === $target) {",
      "            return $mid;",
      "        }",
      "        if ($nums[$mid] < $target) {",
      "            $lo = $mid + 1;              // answer lies to the right",
      "        } else {",
      "            $hi = $mid - 1;              // answer lies to the left",
      "        }",
      "    }",
      "    return -1;                           // bounds crossed - not present",
      "}",
      "",
      "echo search([-1, 0, 3, 5, 9, 12], 9), \"\\n\";",
      "// O(log n) - the range halves every iteration",
    ],
    expectedOutput: "4",
  },

  "promise-pool": {
    starter: "<?php\n// PHP has no promises; tasks are plain callables run in order, with `limit`\n// controlling how many are dispatched per batch.\nfunction pool(array $tasks, int $limit): array {\n    // your code here\n    return [];\n}\n\necho implode(\" \", pool([fn() => 1, fn() => 2, fn() => 3], 2)), \"\\n\";  // 1 2 3",
    solution: [
      "<?php",
      "// PHP has no promises or threads here, so the pool runs tasks in batches of",
      "// `limit`. The property that matters - results ordered by input index, never",
      "// more than `limit` in flight - is preserved.",
      "function pool(array $tasks, int $limit): array {",
      "    $results = [];                       // indexed by position, not finish order",
      "    foreach (array_chunk($tasks, $limit, true) as $batch) {",
      "        foreach ($batch as $i => $task) {",
      "            $results[$i] = $task();      // each writes its own slot",
      "        }",
      "    }",
      "    ksort($results);                     // restore input order",
      "    return $results;",
      "}",
      "",
      "echo implode(\" \", pool([fn() => 1, fn() => 2, fn() => 3], 2)), \"\\n\";",
      "// at most `limit` per batch, results keep their input order",
    ],
    expectedOutput: "1 2 3",
  },

  "group-anagrams": {
    starter: "<?php\nfunction groupAnagrams(array $strs): array {\n    // your code here\n    return [];\n}\n\nforeach (groupAnagrams([\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]) as $g) {\n    echo implode(\",\", $g), \" \";\n}\necho \"\\n\";",
    solution: [
      "<?php",
      "function groupAnagrams(array $strs): array {",
      "    $groups = [];",
      "    foreach ($strs as $w) {",
      "        $letters = str_split($w);",
      "        sort($letters);                  // anagrams share sorted letters,",
      "        $key = implode(\"\", $letters);    // so that is a stable group key",
      "        $groups[$key][] = $w;",
      "    }",
      "    return array_values($groups);",
      "}",
      "",
      "foreach (groupAnagrams([\"eat\", \"tea\", \"tan\", \"ate\", \"nat\", \"bat\"]) as $g) {",
      "    echo implode(\",\", $g), \" \";",
      "}",
      "echo \"\\n\";",
      "// O(n * k log k) for n words of length k",
    ],
    expectedOutput: "eat,tea,ate tan,nat bat",
  },

  "flatten": {
    starter: "<?php\nfunction flatten(array $arr): array {\n    // your code here\n    return [];\n}\n\necho implode(\" \", flatten([1, [2, [3, [4]]]])), \"\\n\";  // 1 2 3 4",
    solution: [
      "<?php",
      "function flatten(array $arr): array {",
      "    $out = [];",
      "    foreach ($arr as $x) {",
      "        // recurse into nested arrays, keep every other value as it is",
      "        if (is_array($x)) {",
      "            $out = array_merge($out, flatten($x));",
      "        } else {",
      "            $out[] = $x;",
      "        }",
      "    }",
      "    return $out;",
      "}",
      "",
      "echo implode(\" \", flatten([1, [2, [3, [4]]]])), \"\\n\";",
      "// visits every element once - O(total elements)",
    ],
    expectedOutput: "1 2 3 4",
  },

  "longest-unique-substring": {
    starter: "<?php\nfunction lengthOfLongestSubstring(string $s): int {\n    // your code here\n    return 0;\n}\n\necho lengthOfLongestSubstring(\"abcabcbb\"), \"\\n\";  // 3",
    solution: [
      "<?php",
      "function lengthOfLongestSubstring(string $s): int {",
      "    $seen = [];                          // char => last index it appeared at",
      "    $best = 0;",
      "    $start = 0;                          // left edge of the window",
      "    for ($i = 0; $i < strlen($s); $i++) {",
      "        $ch = $s[$i];",
      "        // only move the window forward, never back past $start",
      "        if (isset($seen[$ch]) && $seen[$ch] >= $start) {",
      "            $start = $seen[$ch] + 1;",
      "        }",
      "        $seen[$ch] = $i;",
      "        $best = max($best, $i - $start + 1);   // window size",
      "    }",
      "    return $best;",
      "}",
      "",
      "echo lengthOfLongestSubstring(\"abcabcbb\"), \"\\n\";",
      "// sliding window - O(n), each character handled once",
    ],
    expectedOutput: "3",
  },

  "merge-intervals": {
    starter: "<?php\nfunction merge(array $intervals): array {\n    // your code here\n    return [];\n}\n\nforeach (merge([[1, 3], [2, 6], [8, 10], [15, 18]]) as $iv) {\n    echo \"[\", $iv[0], \",\", $iv[1], \"] \";\n}\necho \"\\n\";",
    solution: [
      "<?php",
      "function merge(array $intervals): array {",
      "    // sort by start so any overlaps end up next to each other",
      "    usort($intervals, fn($a, $b) => $a[0] <=> $b[0]);",
      "    $out = [];",
      "    foreach ($intervals as $iv) {",
      "        $last = count($out) - 1;",
      "        // starts before the previous one ended -> overlap, so stretch it",
      "        if ($last >= 0 && $iv[0] <= $out[$last][1]) {",
      "            $out[$last][1] = max($out[$last][1], $iv[1]);",
      "            continue;",
      "        }",
      "        $out[] = [$iv[0], $iv[1]];       // no overlap: begin a new range",
      "    }",
      "    return $out;",
      "}",
      "",
      "foreach (merge([[1, 3], [2, 6], [8, 10], [15, 18]]) as $iv) {",
      "    echo \"[\", $iv[0], \",\", $iv[1], \"] \";",
      "}",
      "echo \"\\n\";",
      "// O(n log n), dominated by the sort",
    ],
    expectedOutput: "[1,6] [8,10] [15,18]",
  },

  "reverse-list": {
    starter: "<?php\nclass Node {\n    public function __construct(public int $val, public ?Node $next = null) {}\n}\n\nfunction reverseList(?Node $head): ?Node {\n    // your code here\n    return null;\n}\n\nfor ($r = reverseList(new Node(1, new Node(2, new Node(3)))); $r; $r = $r->next) {\n    echo $r->val, \" \";\n}\necho \"\\n\";  // 3 2 1",
    solution: [
      "<?php",
      "class Node {",
      "    public function __construct(public int $val, public ?Node $next = null) {}",
      "}",
      "",
      "function reverseList(?Node $head): ?Node {",
      "    $prev = null;",
      "    $cur = $head;",
      "    while ($cur !== null) {",
      "        $next = $cur->next;   // save the rest before overwriting the link",
      "        $cur->next = $prev;   // point this node backwards",
      "        $prev = $cur;         // prev follows cur forward",
      "        $cur = $next;         // carry on down the original list",
      "    }",
      "    return $prev;             // cur is null, so prev is the new head",
      "}",
      "",
      "for ($r = reverseList(new Node(1, new Node(2, new Node(3)))); $r; $r = $r->next) {",
      "    echo $r->val, \" \";",
      "}",
      "echo \"\\n\";",
      "// O(n) time, O(1) space - three pointers, no new nodes",
    ],
    expectedOutput: "3 2 1",
  },

  "search-rotated": {
    starter: "<?php\nfunction searchRotated(array $nums, int $target): int {\n    // your code here\n    return -1;\n}\n\necho searchRotated([4, 5, 6, 7, 0, 1, 2], 0), \"\\n\";  // 4",
    solution: [
      "<?php",
      "function searchRotated(array $nums, int $target): int {",
      "    $lo = 0;",
      "    $hi = count($nums) - 1;",
      "    while ($lo <= $hi) {",
      "        $mid = intdiv($lo + $hi, 2);",
      "        if ($nums[$mid] === $target) {",
      "            return $mid;",
      "        }",
      "        // whatever the rotation, one side of mid is always sorted",
      "        if ($nums[$lo] <= $nums[$mid]) {          // left half is sorted",
      "            // inside that range? search it, otherwise take the other half",
      "            if ($nums[$lo] <= $target && $target < $nums[$mid]) {",
      "                $hi = $mid - 1;",
      "            } else {",
      "                $lo = $mid + 1;",
      "            }",
      "        } else {                                  // right half is sorted",
      "            if ($nums[$mid] < $target && $target <= $nums[$hi]) {",
      "                $lo = $mid + 1;",
      "            } else {",
      "                $hi = $mid - 1;",
      "            }",
      "        }",
      "    }",
      "    return -1;",
      "}",
      "",
      "echo searchRotated([4, 5, 6, 7, 0, 1, 2], 0), \"\\n\";",
      "// still O(log n) - one comparison discards half the range",
    ],
    expectedOutput: "4",
  },

  "num-islands-dfs": {
    starter: "<?php\nfunction numIslands(array $grid): int {\n    // your code here\n    return 0;\n}\n\necho numIslands([\n    [\"1\", \"1\", \"0\"],\n    [\"1\", \"1\", \"0\"],\n    [\"0\", \"0\", \"0\"],\n]), \"\\n\";  // 1",
    solution: [
      "<?php",
      "// flood fill: sink every cell of an island so it is counted only once",
      "function sink(array &$grid, int $r, int $c): void {",
      "    if ($r < 0 || $c < 0 || $r >= count($grid) || $c >= count($grid[0])) {",
      "        return;                          // off the grid",
      "    }",
      "    if ($grid[$r][$c] !== \"1\") {",
      "        return;                          // water, or already sunk",
      "    }",
      "    $grid[$r][$c] = \"0\";                 // mark visited",
      "    sink($grid, $r + 1, $c);",
      "    sink($grid, $r - 1, $c);",
      "    sink($grid, $r, $c + 1);",
      "    sink($grid, $r, $c - 1);",
      "}",
      "",
      "function numIslands(array $grid): int {",
      "    $count = 0;",
      "    for ($r = 0; $r < count($grid); $r++) {",
      "        for ($c = 0; $c < count($grid[0]); $c++) {",
      "            // each land cell still standing begins exactly one new island",
      "            if ($grid[$r][$c] === \"1\") {",
      "                $count++;",
      "                sink($grid, $r, $c);",
      "            }",
      "        }",
      "    }",
      "    return $count;",
      "}",
      "",
      "echo numIslands([",
      "    [\"1\", \"1\", \"0\"],",
      "    [\"1\", \"1\", \"0\"],",
      "    [\"0\", \"0\", \"0\"],",
      "]), \"\\n\";",
      "// O(rows * cols) - each cell is touched a constant number of times",
    ],
    expectedOutput: "1",
  },

  "top-k-frequent-bucket": {
    starter: "<?php\nfunction topKFrequent(array $nums, int $k): array {\n    // your code here\n    return [];\n}\n\necho implode(\" \", topKFrequent([1, 1, 1, 2, 2, 3], 2)), \"\\n\";  // 1 2",
    solution: [
      "<?php",
      "function topKFrequent(array $nums, int $k): array {",
      "    $freq = array_count_values($nums);   // value => how often it appears",
      "    // buckets[i] holds every value seen exactly i times; i never exceeds n",
      "    $buckets = array_fill(0, count($nums) + 1, []);",
      "    foreach ($freq as $n => $c) {",
      "        $buckets[$c][] = $n;",
      "    }",
      "    $out = [];",
      "    // walk down from the highest possible count until we have k values",
      "    for ($c = count($buckets) - 1; $c >= 0 && count($out) < $k; $c--) {",
      "        $out = array_merge($out, $buckets[$c]);",
      "    }",
      "    $out = array_slice($out, 0, $k);     // trim any overshoot",
      "    sort($out);",
      "    return $out;",
      "}",
      "",
      "echo implode(\" \", topKFrequent([1, 1, 1, 2, 2, 3], 2)), \"\\n\";",
      "// bucket sort - O(n), beats a heap's O(n log k) here",
    ],
    expectedOutput: "1 2",
  },

  "climb-stairs-dp": {
    starter: "<?php\nfunction climbStairs(int $n): int {\n    // your code here\n    return 0;\n}\n\necho climbStairs(5), \"\\n\";  // 8",
    solution: [
      "<?php",
      "function climbStairs(int $n): int {",
      "    // step n is reached from n-1 (one step) or n-2 (two), so counts add",
      "    $a = 1;",
      "    $b = 1;                              // ways to stand at step 0 and step 1",
      "    for ($i = 2; $i <= $n; $i++) {",
      "        [$a, $b] = [$b, $a + $b];        // slide the two-value window forward",
      "    }",
      "    return $b;",
      "}",
      "",
      "echo climbStairs(5), \"\\n\";",
      "// Fibonacci in disguise - O(n) time, O(1) space",
    ],
    expectedOutput: "8",
  },

  "url-shortener": {
    starter: "<?php\nclass UrlShortener {\n    public function shorten(string $url): string {\n        // your code here\n        return \"\";\n    }\n\n    public function expand(string $short): ?string {\n        // your code here\n        return null;\n    }\n}\n\n$s = new UrlShortener();\n$short = $s->shorten(\"https://example.com\");\necho $short, \" \", $s->expand($short), \"\\n\";",
    solution: [
      "<?php",
      "const CHARS = \"abcdefghijklmnopqrstuvwxyz\" .",
      "    \"ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789\";",
      "",
      "// turn a counter into a short slug - 62 symbols per character",
      "function base62(int $n): string {",
      "    $s = \"\";",
      "    do {",
      "        $s = CHARS[$n % 62] . $s;        // lowest base-62 digit first",
      "        $n = intdiv($n, 62);             // shift right one digit",
      "    } while ($n > 0);",
      "    return $s;",
      "}",
      "",
      "class UrlShortener {",
      "    private array $urls = [];            // slug => url",
      "    private int $next = 1;               // a counter, not a hash - no collisions",
      "",
      "    public function shorten(string $url): string {",
      "        $slug = base62($this->next++);   // consume one counter value",
      "        $this->urls[$slug] = $url;",
      "        return \"sho.rt/\" . $slug;",
      "    }",
      "",
      "    public function expand(string $short): ?string {",
      "        // accept a full short link or a bare slug",
      "        $parts = explode(\"/\", $short);",
      "        $slug = end($parts);",
      "        return $this->urls[$slug] ?? null;",
      "    }",
      "}",
      "",
      "$s = new UrlShortener();",
      "$short = $s->shorten(\"https://example.com\");",
      "echo $short, \" \", $s->expand($short), \"\\n\";",
      "// 7 chars of base62 is about 3.5 trillion ids",
    ],
    expectedOutput: "sho.rt/b https://example.com",
  },

  "sliding-window-limiter": {
    starter: "<?php\nclass SlidingWindowLimiter {\n    public function __construct(private int $limit, private int $windowMs) {\n        // your code here\n    }\n\n    public function allow(string $key): bool {\n        // your code here\n        return false;\n    }\n}\n\n$l = new SlidingWindowLimiter(2, 1000);\necho implode(\" \", [\n    $l->allow(\"a\") ? \"true\" : \"false\",\n    $l->allow(\"a\") ? \"true\" : \"false\",\n    $l->allow(\"a\") ? \"true\" : \"false\",\n]), \"\\n\";",
    solution: [
      "<?php",
      "class SlidingWindowLimiter {",
      "    private array $hits = [];            // key => timestamps of recent calls",
      "",
      "    public function __construct(private int $limit, private int $windowMs) {}",
      "",
      "    public function allow(string $key): bool {",
      "        $now = microtime(true) * 1000;",
      "        // drop timestamps that aged out - this is what makes it \"sliding\"",
      "        $log = array_values(array_filter(",
      "            $this->hits[$key] ?? [],",
      "            fn($t) => $now - $t < $this->windowMs",
      "        ));",
      "        if (count($log) >= $this->limit) {",
      "            $this->hits[$key] = $log;",
      "            return false;                // budget already spent",
      "        }",
      "        $log[] = $now;                   // record this call",
      "        $this->hits[$key] = $log;",
      "        return true;",
      "    }",
      "}",
      "",
      "$l = new SlidingWindowLimiter(2, 1000);",
      "$out = [];",
      "foreach ([1, 2, 3] as $_) {",
      "    $out[] = $l->allow(\"a\") ? \"true\" : \"false\";",
      "}",
      "echo implode(\" \", $out), \"\\n\";",
      "// exact, but O(hits) memory - a token bucket scales better",
    ],
    expectedOutput: "true true false",
  },

  "throttle": {
    starter: "<?php\n// PHP has no event loop here, so throttle is modelled as \"let a call through\n// only once per window\", checked against the wall clock.\nclass Throttler {\n    public function __construct(private float $waitMs) {\n        // your code here\n    }\n\n    public function call(callable $fn): void {\n        // your code here\n    }\n}\n\n$n = 0;\n$t = new Throttler(80);\n$t->call(function () use (&$n) { $n++; });\n$t->call(function () use (&$n) { $n++; });\necho $n, \"\\n\";  // 1",
    solution: [
      "<?php",
      "// PHP has no event loop here, so there is no trailing timer to schedule.",
      "// Throttle keeps the property that survives translation: a call is let",
      "// through at most once per window, checked against the wall clock.",
      "class Throttler {",
      "    private float $last = 0;",
      "",
      "    public function __construct(private float $waitMs) {}",
      "",
      "    public function call(callable $fn): void {",
      "        $now = microtime(true) * 1000;",
      "        if ($now - $this->last < $this->waitMs) {",
      "            return;                      // window still closed - drop the call",
      "        }",
      "        $this->last = $now;              // window open - fire and reset it",
      "        $fn();",
      "    }",
      "}",
      "",
      "$n = 0;",
      "$t = new Throttler(80);",
      "$bump = function () use (&$n) { $n++; };",
      "$t->call($bump);",
      "$t->call($bump);                         // inside the window - dropped",
      "$t->call($bump);",
      "usleep(120000);                          // wait past the window",
      "$t->call($bump);                         // window reopened - fires",
      "echo $n, \"\\n\";",
      "// leading edge only: the first call of each window gets through",
    ],
    expectedOutput: "2",
  },
};
