import type { LangTable } from "./index";

/** Python 3 starters and reference solutions. Verified by npm run verify:solutions. */
export const PYTHON: LangTable = {
  "two-sum": {
    starter: 'def two_sum(nums, target):\n    # your code here\n    pass\n\n\nprint(two_sum([2, 7, 11, 15], 9))  # [0, 1]',
    solution: [
      "def two_sum(nums, target):",
      "    seen = {}                       # value -> index",
      "    for i, n in enumerate(nums):",
      "        need = target - n",
      "        if need in seen:",
      "            return [seen[need], i]",
      "        seen[n] = i",
      "    return []",
      "",
      "",
      "print(two_sum([2, 7, 11, 15], 9))",
      "# O(n) time, O(n) space",
    ],
    expectedOutput: "[0, 1]",
  },

  "max-subarray": {
    starter: "def max_sub_array(nums):\n    # your code here\n    pass\n\n\nprint(max_sub_array([-2, 1, -3, 4, -1, 2, 1, -5, 4]))  # 6",
    solution: [
      "def max_sub_array(nums):",
      "    best = cur = nums[0]",
      "    for n in nums[1:]:",
      "        # either extend the run, or start fresh at n",
      "        cur = max(n, cur + n)",
      "        best = max(best, cur)",
      "    return best",
      "",
      "",
      "print(max_sub_array([-2, 1, -3, 4, -1, 2, 1, -5, 4]))",
      "# Kadane's algorithm - O(n)",
    ],
    expectedOutput: "6",
  },

  "valid-parens": {
    starter: 'def is_valid(s):\n    # your code here\n    pass\n\n\nprint(is_valid("()[]{}"))  # True',
    solution: [
      "def is_valid(s):",
      "    pairs = {')': '(', ']': '[', '}': '{'}",
      "    stack = []",
      "    for ch in s:",
      "        if ch in pairs:",
      "            if not stack or stack.pop() != pairs[ch]:",
      "                return False",
      "        else:",
      "            stack.append(ch)",
      "    return not stack       # anything left open is invalid",
      "",
      "",
      'print(is_valid("()[]{}"))',
    ],
    expectedOutput: "True",
  },

  lru: {
    starter:
      "class LRUCache:\n    def __init__(self, cap):\n        # your code here\n        pass\n\n    def get(self, k):\n        pass\n\n    def put(self, k, v):\n        pass\n\n\nc = LRUCache(2)\nc.put(1, 1)\nc.put(2, 2)\nprint(c.get(1))  # 1",
    solution: [
      "from collections import OrderedDict",
      "",
      "",
      "class LRUCache:",
      "    def __init__(self, cap):",
      "        self.cap = cap",
      "        self.m = OrderedDict()",
      "",
      "    def get(self, k):",
      "        if k not in self.m:",
      "            return -1",
      "        self.m.move_to_end(k)        # mark as most-recent",
      "        return self.m[k]",
      "",
      "    def put(self, k, v):",
      "        if k in self.m:",
      "            self.m.move_to_end(k)",
      "        self.m[k] = v",
      "        if len(self.m) > self.cap:",
      "            self.m.popitem(last=False)   # evict least-recent",
      "",
      "",
      "c = LRUCache(2)",
      "c.put(1, 1)",
      "c.put(2, 2)",
      "print(c.get(1))",
      "c.put(3, 3)",
      "print(c.get(2))",
    ],
    expectedOutput: "1\n-1",
  },

  "rate-limiter": {
    starter:
      "import time\n\n\nclass RateLimiter:\n    def __init__(self, rate, per):\n        # your code here\n        pass\n\n    def allow(self):\n        pass\n\n\nr = RateLimiter(2, 1.0)\nprint([r.allow(), r.allow(), r.allow()])  # [True, True, False]",
    solution: [
      "import time",
      "",
      "",
      "class RateLimiter:",
      "    def __init__(self, rate, per):",
      "        self.rate = rate",
      "        self.per = per            # window length in seconds",
      "        self.tokens = float(rate)",
      "        self.last = time.time()",
      "",
      "    def allow(self):",
      "        now = time.time()",
      "        # refill proportionally to time elapsed",
      "        self.tokens += ((now - self.last) / self.per) * self.rate",
      "        self.tokens = min(self.tokens, self.rate)",
      "        self.last = now",
      "        if self.tokens < 1:",
      "            return False",
      "        self.tokens -= 1",
      "        return True",
      "",
      "",
      "r = RateLimiter(2, 1.0)",
      "print([r.allow(), r.allow(), r.allow()])",
    ],
    expectedOutput: "[True, True, False]",
  },

  debounce: {
    starter:
      'import threading\nimport time\n\n\ndef debounce(fn, wait):\n    # your code here — return the wrapped function\n    return lambda *args, **kwargs: None\n\n\ncalls = []\nf = debounce(lambda v: calls.append(v), 0.05)\nf("a")\nf("b")\ntime.sleep(0.2)\nprint(calls)  # [\'b\']',
    solution: [
      "import threading",
      "import time",
      "",
      "",
      "def debounce(fn, wait):",
      '    state = {"timer": None}',
      "",
      "    def wrapped(*args, **kwargs):",
      '        if state["timer"]:',
      '            state["timer"].cancel()      # cancel pending call',
      '        state["timer"] = threading.Timer(wait, fn, args, kwargs)',
      '        state["timer"].start()',
      "",
      "    return wrapped",
      "",
      "",
      "calls = []",
      "f = debounce(lambda v: calls.append(v), 0.05)",
      'f("a")',
      'f("b")',
      "time.sleep(0.2)",
      "print(calls)      # only the last call survives",
    ],
    expectedOutput: "['b']",
  },

  "binary-search": {
    starter: "def search(nums, target):\n    # your code here\n    pass\n\n\nprint(search([-1, 0, 3, 5, 9, 12], 9))  # 4",
    solution: [
      "def search(nums, target):",
      "    lo, hi = 0, len(nums) - 1",
      "    while lo <= hi:",
      "        mid = (lo + hi) // 2",
      "        if nums[mid] == target:",
      "            return mid",
      "        if nums[mid] < target:",
      "            lo = mid + 1",
      "        else:",
      "            hi = mid - 1",
      "    return -1",
      "",
      "",
      "print(search([-1, 0, 3, 5, 9, 12], 9))",
      "# O(log n)",
    ],
    expectedOutput: "4",
  },

  "promise-pool": {
    starter:
      "import asyncio\n\n\nasync def pool(tasks, limit):\n    # your code here\n    pass\n\n\nasync def main():\n    async def mk(v):\n        await asyncio.sleep(0.01)\n        return v\n\n    print(await pool([lambda: mk(1), lambda: mk(2), lambda: mk(3)], 2))\n\n\nasyncio.run(main())  # [1, 2, 3]",
    solution: [
      "import asyncio",
      "",
      "",
      "async def pool(tasks, limit):",
      "    sem = asyncio.Semaphore(limit)    # caps how many run at once",
      "",
      "    async def run(i, task):",
      "        async with sem:",
      "            return i, await task()",
      "",
      "    done = await asyncio.gather(*(run(i, t) for i, t in enumerate(tasks)))",
      "    out = [None] * len(tasks)",
      "    for i, v in done:",
      "        out[i] = v               # restore input order",
      "    return out",
      "",
      "",
      "async def main():",
      "    async def mk(v):",
      "        await asyncio.sleep(0.01)",
      "        return v",
      "",
      "    print(await pool([lambda: mk(1), lambda: mk(2), lambda: mk(3)], 2))",
      "",
      "",
      "asyncio.run(main())",
    ],
    expectedOutput: "[1, 2, 3]",
  },

  "group-anagrams": {
    starter:
      'def group_anagrams(strs):\n    # your code here\n    pass\n\n\nprint(group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]))',
    solution: [
      "from collections import defaultdict",
      "",
      "",
      "def group_anagrams(strs):",
      "    groups = defaultdict(list)",
      "    for w in strs:",
      "        # sorted letters are identical for anagrams",
      '        groups["".join(sorted(w))].append(w)',
      "    return list(groups.values())",
      "",
      "",
      'print(group_anagrams(["eat", "tea", "tan", "ate", "nat", "bat"]))',
    ],
    expectedOutput: "[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]",
  },

  flatten: {
    starter: "def flatten(arr):\n    # your code here\n    pass\n\n\nprint(flatten([1, [2, [3, [4]]]]))  # [1, 2, 3, 4]",
    solution: [
      "def flatten(arr):",
      "    out = []",
      "    for x in arr:",
      "        if isinstance(x, list):",
      "            out.extend(flatten(x))   # recurse into nested lists",
      "        else:",
      "            out.append(x)",
      "    return out",
      "",
      "",
      "print(flatten([1, [2, [3, [4]]]]))",
    ],
    expectedOutput: "[1, 2, 3, 4]",
  },

  "longest-unique-substring": {
    starter:
      'def length_of_longest_substring(s):\n    # your code here\n    pass\n\n\nprint(length_of_longest_substring("abcabcbb"))  # 3',
    solution: [
      "def length_of_longest_substring(s):",
      "    seen = {}                    # char -> last index seen",
      "    best = start = 0",
      "    for i, ch in enumerate(s):",
      "        if ch in seen and seen[ch] >= start:",
      "            start = seen[ch] + 1     # slide the window past the repeat",
      "        seen[ch] = i",
      "        best = max(best, i - start + 1)",
      "    return best",
      "",
      "",
      'print(length_of_longest_substring("abcabcbb"))',
    ],
    expectedOutput: "3",
  },

  "merge-intervals": {
    starter:
      "def merge(intervals):\n    # your code here\n    pass\n\n\nprint(merge([[1, 3], [2, 6], [8, 10], [15, 18]]))",
    solution: [
      "def merge(intervals):",
      "    intervals.sort(key=lambda iv: iv[0])",
      "    out = []",
      "    for s, e in intervals:",
      "        # overlaps the previous range -> stretch it",
      "        if out and s <= out[-1][1]:",
      "            out[-1][1] = max(out[-1][1], e)",
      "        else:",
      "            out.append([s, e])",
      "    return out",
      "",
      "",
      "print(merge([[1, 3], [2, 6], [8, 10], [15, 18]]))",
      "# O(n log n), dominated by the sort",
    ],
    expectedOutput: "[[1, 6], [8, 10], [15, 18]]",
  },

  "reverse-list": {
    starter:
      "class Node:\n    def __init__(self, val, nxt=None):\n        self.val = val\n        self.next = nxt\n\n\ndef reverse_list(head):\n    # your code here\n    pass\n\n\nr = reverse_list(Node(1, Node(2, Node(3))))\nout = []\nwhile r:\n    out.append(r.val)\n    r = r.next\nprint(out)  # [3, 2, 1]",
    solution: [
      "class Node:",
      "    def __init__(self, val, nxt=None):",
      "        self.val = val",
      "        self.next = nxt",
      "",
      "",
      "def reverse_list(head):",
      "    prev, cur = None, head",
      "    while cur:",
      "        nxt = cur.next        # hold the rest of the list",
      "        cur.next = prev       # flip this link",
      "        prev, cur = cur, nxt",
      "    return prev               # prev is the new head",
      "",
      "",
      "r = reverse_list(Node(1, Node(2, Node(3))))",
      "out = []",
      "while r:",
      "    out.append(r.val)",
      "    r = r.next",
      "print(out)",
    ],
    expectedOutput: "[3, 2, 1]",
  },

  "search-rotated": {
    starter:
      "def search_rotated(nums, target):\n    # your code here\n    pass\n\n\nprint(search_rotated([4, 5, 6, 7, 0, 1, 2], 0))  # 4",
    solution: [
      "def search_rotated(nums, target):",
      "    lo, hi = 0, len(nums) - 1",
      "    while lo <= hi:",
      "        mid = (lo + hi) // 2",
      "        if nums[mid] == target:",
      "            return mid",
      "        if nums[lo] <= nums[mid]:        # left half is sorted",
      "            if nums[lo] <= target < nums[mid]:",
      "                hi = mid - 1",
      "            else:",
      "                lo = mid + 1",
      "        else:                            # right half is sorted",
      "            if nums[mid] < target <= nums[hi]:",
      "                lo = mid + 1",
      "            else:",
      "                hi = mid - 1",
      "    return -1",
      "",
      "",
      "print(search_rotated([4, 5, 6, 7, 0, 1, 2], 0))",
    ],
    expectedOutput: "4",
  },

  "num-islands-dfs": {
    starter:
      'def num_islands(grid):\n    # your code here\n    pass\n\n\nprint(num_islands([["1", "1", "0"], ["1", "1", "0"], ["0", "0", "0"]]))  # 1',
    solution: [
      "import sys",
      "",
      "sys.setrecursionlimit(10000)",
      "",
      "",
      "def num_islands(grid):",
      "    if not grid:",
      "        return 0",
      "    rows, cols = len(grid), len(grid[0])",
      "",
      "    def sink(r, c):",
      "        if r < 0 or c < 0 or r >= rows or c >= cols:",
      "            return",
      '        if grid[r][c] != "1":',
      "            return",
      '        grid[r][c] = "0"          # mark as visited',
      "        sink(r + 1, c)",
      "        sink(r - 1, c)",
      "        sink(r, c + 1)",
      "        sink(r, c - 1)",
      "",
      "    count = 0",
      "    for r in range(rows):",
      "        for c in range(cols):",
      '            if grid[r][c] == "1":',
      "                count += 1",
      "                sink(r, c)",
      "    return count",
      "",
      "",
      'print(num_islands([["1", "1", "0"], ["1", "1", "0"], ["0", "0", "0"]]))',
    ],
    expectedOutput: "1",
  },

  "top-k-frequent-bucket": {
    starter:
      "def top_k_frequent(nums, k):\n    # your code here\n    pass\n\n\nprint(top_k_frequent([1, 1, 1, 2, 2, 3], 2))  # [1, 2]",
    solution: [
      "from collections import Counter",
      "",
      "",
      "def top_k_frequent(nums, k):",
      "    freq = Counter(nums)",
      "    # buckets[i] holds every value seen exactly i times",
      "    buckets = [[] for _ in range(len(nums) + 1)]",
      "    for n, c in freq.items():",
      "        buckets[c].append(n)",
      "    out = []",
      "    for c in range(len(buckets) - 1, 0, -1):",
      "        out.extend(buckets[c])",
      "        if len(out) >= k:",
      "            break",
      "    return out[:k]",
      "",
      "",
      "print(top_k_frequent([1, 1, 1, 2, 2, 3], 2))",
      "# bucket sort - O(n), beats a heap here",
    ],
    expectedOutput: "[1, 2]",
  },

  "climb-stairs-dp": {
    starter: "def climb_stairs(n):\n    # your code here\n    pass\n\n\nprint(climb_stairs(5))  # 8",
    solution: [
      "def climb_stairs(n):",
      "    # ways(n) = ways(n-1) + ways(n-2) - it is Fibonacci",
      "    a, b = 1, 1",
      "    for _ in range(n - 1):",
      "        a, b = b, a + b",
      "    return b",
      "",
      "",
      "print(climb_stairs(5))",
      "# O(n) time, O(1) space",
    ],
    expectedOutput: "8",
  },

  "url-shortener": {
    starter:
      'class UrlShortener:\n    def __init__(self):\n        # your code here\n        pass\n\n    def shorten(self, url):\n        pass\n\n    def expand(self, short):\n        pass\n\n\ns = UrlShortener()\nshort = s.shorten("https://example.com")\nprint(short, s.expand(short))',
    solution: [
      'CHARS = "abcdefghijklmnopqrstuvwxyz" \\',
      '        "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"',
      "",
      "",
      "def base62(n):",
      '    s = ""',
      "    while True:",
      "        s = CHARS[n % 62] + s",
      "        n //= 62",
      "        if n == 0:",
      "            return s",
      "",
      "",
      "class UrlShortener:",
      "    def __init__(self):",
      "        self.urls = {}",
      "        self.next = 1",
      "",
      "    def shorten(self, url):",
      "        # a counter, not a hash - so slugs never collide",
      "        slug = base62(self.next)",
      "        self.next += 1",
      "        self.urls[slug] = url",
      '        return "sho.rt/" + slug',
      "",
      "    def expand(self, short):",
      '        return self.urls.get(short.split("/")[-1])',
      "",
      "",
      "s = UrlShortener()",
      'short = s.shorten("https://example.com")',
      "print(short, s.expand(short))",
    ],
    expectedOutput: "sho.rt/b https://example.com",
  },

  "sliding-window-limiter": {
    starter:
      'import time\n\n\nclass SlidingWindowLimiter:\n    def __init__(self, limit, window):\n        # your code here\n        pass\n\n    def allow(self, key):\n        pass\n\n\nl = SlidingWindowLimiter(2, 1.0)\nprint([l.allow("a"), l.allow("a"), l.allow("a")])',
    solution: [
      "import time",
      "",
      "",
      "class SlidingWindowLimiter:",
      "    def __init__(self, limit, window):",
      "        self.limit = limit",
      "        self.window = window          # seconds",
      "        self.hits = {}                # key -> timestamps",
      "",
      "    def allow(self, key):",
      "        now = time.time()",
      "        # drop anything that fell out of the window",
      "        log = [t for t in self.hits.get(key, []) if now - t < self.window]",
      "        self.hits[key] = log",
      "        if len(log) >= self.limit:",
      "            return False",
      "        log.append(now)",
      "        return True",
      "",
      "",
      "l = SlidingWindowLimiter(2, 1.0)",
      'print([l.allow("a"), l.allow("a"), l.allow("a")])',
      "# exact, but O(hits) memory - token bucket scales better",
    ],
    expectedOutput: "[True, True, False]",
  },

  throttle: {
    starter:
      "import threading\nimport time\n\n\ndef throttle(fn, wait):\n    # your code here — return the wrapped function\n    return lambda *args: None\n\n\ncalls = []\nf = throttle(lambda: calls.append(1), 0.08)\nf()\nf()\nf()\ntime.sleep(0.25)\nprint(len(calls))  # 2",
    solution: [
      "import threading",
      "import time",
      "",
      "",
      "def throttle(fn, wait):",
      '    state = {"last": 0.0, "timer": None}',
      "",
      "    def wrapped(*args):",
      "        now = time.time()",
      '        left = wait - (now - state["last"])',
      "        if left <= 0:                 # window open - fire now",
      '            state["last"] = now',
      "            fn(*args)",
      '        elif state["timer"] is None:  # queue the trailing call',
      "            def fire():",
      '                state["last"] = time.time()',
      '                state["timer"] = None',
      "                fn(*args)",
      "",
      '            state["timer"] = threading.Timer(left, fire)',
      '            state["timer"].start()',
      "",
      "    return wrapped",
      "",
      "",
      "calls = []",
      "f = throttle(lambda: calls.append(1), 0.08)",
      "f()",
      "f()",
      "f()",
      "time.sleep(0.25)",
      "print(len(calls))     # one leading + one trailing",
    ],
    expectedOutput: "2",
  },
};
